<?php
/**
 * Copy Right IJH.CC
 * Each engineer has a duty to keep the code elegant
 * $Id$
 */

if(!defined('__CORE_DIR')){
    exit("Access Denied");
}
return array (
  'order_id' => 
  array (
    'field' => 'order_id',
    'label' => 'order_id',
    'pk' => true,
    'add' => true,
    'edit' => false,
    'html' => false,
    'empty' => false,
    'show' => true,
    'list' => true,
    'type' => 'text',
    'comment' => '跑腿订单ID',
    'default' => '',
    'SO' => false,
  ),
  'type' => 
  array (
    'field' => 'type',
    'label' => 'type',
    'pk' => false,
    'add' => true,
    'edit' => true,
    'html' => false,
    'empty' => false,
    'show' => true,
    'list' => true,
    'type' => 'text',
    'comment' => '类型',
    'default' => '',
    'SO' => false,
  ),
  'o_addr' => 
  array (
    'field' => 'o_addr',
    'label' => '取件地址',
    'pk' => false,
    'add' => true,
    'edit' => false,
    'html' => false,
    'empty' => false,
    'show' => true,
    'list' => true,
    'type' => 'text',
    'comment' => '取件地址',
    'default' => '',
    'SO' => 'like',
  ),
  'o_house' => 
  array (
    'field' => 'o_house',
    'label' => '取件门牌号',
    'pk' => false,
    'add' => true,
    'edit' => false,
    'html' => false,
    'empty' => false,
    'show' => true,
    'list' => true,
    'type' => 'text',
    'comment' => '取件门牌号',
    'default' => '',
    'SO' => 'like',
  ),
  'o_contact' => 
  array (
    'field' => 'o_contact',
    'label' => '取件联系人',
    'pk' => false,
    'add' => true,
    'edit' => false,
    'html' => false,
    'empty' => false,
    'show' => true,
    'list' => true,
    'type' => 'text',
    'comment' => '取件联系人',
    'default' => '',
    'SO' => false,
  ),
  'o_mobile' => 
  array (
    'field' => 'o_mobile',
    'label' => '取件联系人电话',
    'pk' => false,
    'add' => true,
    'edit' => false,
    'html' => false,
    'empty' => false,
    'show' => true,
    'list' => true,
    'type' => 'text',
    'comment' => '取件联系人电话',
    'default' => '',
    'SO' => false,
  ),
  'o_lat' => 
  array (
    'field' => 'o_lat',
    'label' => '取件纬度',
    'pk' => false,
    'add' => true,
    'edit' => false,
    'html' => false,
    'empty' => false,
    'show' => true,
    'list' => true,
    'type' => 'text',
    'comment' => '取件纬度坐标',
    'default' => '',
    'SO' => false,
  ),
  'o_lng' => 
  array (
    'field' => 'o_lng',
    'label' => '取件经度',
    'pk' => false,
    'add' => true,
    'edit' => false,
    'html' => false,
    'empty' => false,
    'show' => true,
    'list' => true,
    'type' => 'text',
    'comment' => '取件经度坐标',
    'default' => '',
    'SO' => false,
  ),
  'intro' => 
  array (
    'field' => 'intro',
    'label' => '描述',
    'pk' => false,
    'add' => true,
    'edit' => false,
    'html' => false,
    'empty' => false,
    'show' => true,
    'list' => true,
    'type' => 'text',
    'comment' => '描述',
    'default' => '',
    'SO' => false,
  ),
  'photo' => 
  array (
    'field' => 'photo',
    'label' => '图片',
    'pk' => false,
    'add' => true,
    'edit' => false,
    'html' => false,
    'empty' => false,
    'show' => true,
    'list' => true,
    'type' => 'text',
    'comment' => '图片',
    'default' => '',
    'SO' => false,
  ),
  'voice' => 
  array (
    'field' => 'voice',
    'label' => '语音',
    'pk' => false,
    'add' => true,
    'edit' => false,
    'html' => false,
    'empty' => false,
    'show' => true,
    'list' => true,
    'type' => 'text',
    'comment' => '语音',
    'default' => '',
    'SO' => false,
  ),
  'voice_time' => 
  array (
    'field' => 'voice_time',
    'label' => '语音时间',
    'pk' => false,
    'add' => true,
    'edit' => false,
    'html' => false,
    'empty' => false,
    'show' => true,
    'list' => true,
    'type' => 'text',
    'comment' => '语音时间',
    'default' => '0',
    'SO' => false,
  ),
  'paotui_amount' => 
  array (
    'field' => 'paotui_amount',
    'label' => '跑腿费用',
    'pk' => false,
    'add' => true,
    'edit' => false,
    'html' => false,
    'empty' => false,
    'show' => true,
    'list' => true,
    'type' => 'text',
    'comment' => '跑腿费用',
    'default' => '0.00',
    'SO' => false,
  ),
  'reward_amount' => 
  array (
    'field' => 'reward_amount',
    'label' => '小费金额',
    'pk' => false,
    'add' => true,
    'edit' => false,
    'html' => false,
    'empty' => false,
    'show' => true,
    'list' => true,
    'type' => 'text',
    'comment' => '小费金额',
    'default' => '0.00',
    'SO' => false,
  ),
);