<?php
/**
 * Copy Right IJH.CC
 * Each engineer has a duty to keep the code elegant
 * $Id$
 */

if(!defined('__CORE_DIR')){
    exit("Access Denied");
}

return array (
  'pintuan_product_id' => 
  array (
    'field' => 'pintuan_product_id',
    'label' => '商品ID',
    'pk' => true,
    'add' => false,
    'edit' => false,
    'html' => false,
    'empty' => false,
    'show' => true,
    'list' => true,
    'type' => 'int',
    'comment' => '商品ID',
    'default' => '',
    'SO' => '=',
  ),
  'shop_id' => 
  array (
    'field' => 'shop_id',
    'label' => '商户ID',
    'pk' => false,
    'add' => true,
    'edit' => true,
    'html' => false,
    'empty' => true,
    'show' => true,
    'list' => true,
    'type' => 'shop',
    'comment' => '商户ID',
    'default' => '',
    'SO' => '=',
  ),
  'cate_id' => 
  array (
    'field' => 'cate_id',
    'label' => '分类ID',
    'pk' => false,
    'add' => true,
    'edit' => true,
    'html' => false,
    'empty' => true,
    'show' => true,
    'list' => true,
    'type' => 'select',
    'comment' => '分类ID',
    'default' => '',
    'SO' => '=',
  ),
  'title' => 
  array (
    'field' => 'title',
    'label' => '商品名称',
    'pk' => false,
    'add' => true,
    'edit' => true,
    'html' => false,
    'empty' => true,
    'show' => true,
    'list' => true,
    'type' => 'text',
    'comment' => '商品名称',
    'default' => '',
    'SO' => 'like',
  ),
  'photo' => 
  array (
    'field' => 'photo',
    'label' => '图片',
    'pk' => false,
    'add' => true,
    'edit' => true,
    'html' => false,
    'empty' => true,
    'show' => true,
    'list' => true,
    'type' => 'photo',
    'comment' => '图片',
    'default' => '',
    'SO' => false,
  ),
  'price' => 
  array (
    'field' => 'price',
    'label' => '价格',
    'pk' => false,
    'add' => true,
    'edit' => true,
    'html' => false,
    'empty' => true,
    'show' => true,
    'list' => true,
    'type' => 'number',
    'comment' => '价格',
    'default' => '0.00',
    'SO' => false,
  ),
  'package_price' => 
  array (
    'field' => 'package_price',
    'label' => '打包费',
    'pk' => false,
    'add' => true,
    'edit' => true,
    'html' => false,
    'empty' => true,
    'show' => true,
    'list' => true,
    'type' => 'number',
    'comment' => '打包费, 0:免打包费',
    'default' => '0.00',
    'SO' => false,
  ),
  'sales' => 
  array (
    'field' => 'sales',
    'label' => '销量',
    'pk' => false,
    'add' => true,
    'edit' => true,
    'html' => false,
    'empty' => true,
    'show' => true,
    'list' => true,
    'type' => 'int',
    'comment' => '销量',
    'default' => '',
    'SO' => false,
  ),
  'intro' => 
  array (
    'field' => 'intro',
    'label' => '描述',
    'pk' => false,
    'add' => true,
    'edit' => true,
    'html' => true,
    'empty' => true,
    'show' => true,
    'list' => false,
    'type' => 'editor',
    'comment' => '描述',
    'default' => '',
    'SO' => false,
  ),
  'item_limit' => 
  array (
    'field' => 'item_limit',
    'label' => '限购数',
    'pk' => false,
    'add' => true,
    'edit' => true,
    'html' => false,
    'empty' => true,
    'show' => true,
    'list' => true,
    'type' => 'int',
    'comment' => '默认:999, 0:不允许单独购买,其他数字: 限购份数上限',
    'default' => '',
    'SO' => false,
  ),
  'tuan_type' => 
  array (
    'field' => 'tuan_type',
    'label' => '团类型',
    'pk' => false,
    'add' => true,
    'edit' => true,
    'html' => false,
    'empty' => true,
    'show' => true,
    'list' => true,
    'type' => 'radio',
    'comment' => '团类型  0:普通团  1:阶梯团(值为1则 user_num 0 和 tuan_price 读取最高阶梯价格)',
    'default' => '',
    'SO' => '=',
  ),
  'user_num' => 
  array (
    'field' => 'user_num',
    'label' => '参团人数(0,不限)',
    'pk' => false,
    'add' => true,
    'edit' => true,
    'html' => false,
    'empty' => true,
    'show' => true,
    'list' => true,
    'type' => 'int',
    'comment' => '几人团,  默认3,    3:默认3人,   0:无上限',
    'default' => '3',
    'SO' => '=',
  ),
  'tuan_price' => 
  array (
    'field' => 'tuan_price',
    'label' => '团购价格',
    'pk' => false,
    'add' => true,
    'edit' => true,
    'html' => false,
    'empty' => true,
    'show' => true,
    'list' => true,
    'type' => 'number',
    'comment' => '团购价格,要低于产品价',
    'default' => '0.00',
    'SO' => '>=',
  ),
  'tuan_time' => 
  array (
    'field' => 'tuan_time',
    'label' => '成团有效期',
    'pk' => false,
    'add' => true,
    'edit' => true,
    'html' => false,
    'empty' => true,
    'show' => true,
    'list' => true,
    'type' => 'int',
    'comment' => '成团有效期,  默认3, 单位天, 2位数,最大99,',
    'default' => '3',
    'SO' => false,
  ),
  'tuan_limit' => 
  array (
    'field' => 'tuan_limit',
    'label' => '团限购',
    'pk' => false,
    'add' => true,
    'edit' => true,
    'html' => false,
    'empty' => true,
    'show' => true,
    'list' => true,
    'type' => 'int',
    'comment' => '团是否限购 默认1  0:否(无上限)   1: 是(上限后需新开一团)',
    'default' => '1',
    'SO' => '=',
  ),
  'master_is_free' => 
  array (
    'field' => 'master_is_free',
    'label' => '团长免单',
    'pk' => false,
    'add' => true,
    'edit' => true,
    'html' => false,
    'empty' => true,
    'show' => true,
    'list' => true,
    'type' => 'radio',
    'comment' => '团长是否免单,  0: 不免单(默认),  1: 免单团长1人',
    'default' => '',
    'SO' => false,
  ),
  'master_need_buy' => 
  array (
    'field' => 'master_need_buy',
    'label' => '需购买开团',
    'pk' => false,
    'add' => true,
    'edit' => true,
    'html' => false,
    'empty' => true,
    'show' => true,
    'list' => true,
    'type' => 'radio',
    'comment' => '团长是否购买才能开团  0:无需购买(默认),  1: 需要购买',
    'default' => '',
    'SO' => false,
  ),
  'money_master' => 
  array (
    'field' => 'money_master',
    'label' => '团长佣金',
    'pk' => false,
    'add' => true,
    'edit' => true,
    'html' => false,
    'empty' => true,
    'show' => true,
    'list' => true,
    'type' => 'number',
    'comment' => '团长佣金,按份?   (总预付款, money_master + money_pre)',
    'default' => '0.00',
    'SO' => false,
  ),
  'money_pre' => 
  array (
    'field' => 'money_pre',
    'label' => '预付定金',
    'pk' => false,
    'add' => true,
    'edit' => true,
    'html' => false,
    'empty' => true,
    'show' => true,
    'list' => true,
    'type' => 'number',
    'comment' => '预付定金 (总预付款, money_master + money_pre)',
    'default' => '0.00',
    'SO' => false,
  ),
  'address_type' => 
  array (
    'field' => 'address_type',
    'label' => '配送类型',
    'pk' => false,
    'add' => true,
    'edit' => true,
    'html' => false,
    'empty' => true,
    'show' => true,
    'list' => true,
    'type' => 'radio',
    'comment' => '配送类型,0:二者都可(默认),  1:仅配送, 2: 仅自提',
    'default' => '',
    'SO' => false,
  ),
  'ship_fee' => 
  array (
    'field' => 'ship_fee',
    'label' => '配送费用',
    'pk' => false,
    'add' => true,
    'edit' => true,
    'html' => false,
    'empty' => true,
    'show' => true,
    'list' => true,
    'type' => 'number',
    'comment' => '配送费用,默认  0,   (仅自提不出现)',
    'default' => '0.00',
    'SO' => false,
  ),
  'stock' => 
  array (
    'field' => 'stock',
    'label' => '库存',
    'pk' => false,
    'add' => true,
    'edit' => true,
    'html' => false,
    'empty' => true,
    'show' => true,
    'list' => true,
    'type' => 'text',
    'comment' => '库存',
    'default' => '',
    'SO' => false,
  ),
  'orderby' => 
  array (
    'field' => 'orderby',
    'label' => '排序',
    'pk' => false,
    'add' => true,
    'edit' => true,
    'html' => false,
    'empty' => true,
    'show' => true,
    'list' => true,
    'type' => 'text',
    'comment' => '排序',
    'default' => '50',
    'SO' => false,
  ),
  'closed' => 
  array (
    'field' => 'closed',
    'label' => '状态',
    'pk' => false,
    'add' => true,
    'edit' => true,
    'html' => false,
    'empty' => true,
    'show' => true,
    'list' => true,
    'type' => 'audit',
    'comment' => '0:关闭  1:开启',
    'default' => '',
    'SO' => false,
  ),
  'clientip' => 
  array (
    'field' => 'clientip',
    'label' => '客户IP',
    'pk' => false,
    'add' => false,
    'edit' => false,
    'html' => false,
    'empty' => true,
    'show' => true,
    'list' => false,
    'type' => 'clientip',
    'comment' => '',
    'default' => '',
    'SO' => false,
  ),
  'dateline' => 
  array (
    'field' => 'dateline',
    'label' => '创建时间',
    'pk' => false,
    'add' => false,
    'edit' => false,
    'html' => false,
    'empty' => true,
    'show' => true,
    'list' => true,
    'type' => 'dateline',
    'comment' => '',
    'default' => '',
    'SO' => false,
  ),
);