<?php
/**
 * Copy Right IJH.CC
 * Each engineer has a duty to keep the code elegant
 * $Id$
 */

if(!defined('__CORE_DIR')){
    exit("Access Denied");
}

return array (
  'pintuan_group_id' => 
  array (
    'field' => 'pintuan_group_id',
    'label' => '团单号',
    'pk' => true,
    'add' => false,
    'edit' => true,
    'html' => false,
    'empty' => false,
    'show' => true,
    'list' => true,
    'type' => 'int',
    'comment' => '团单号,主键,递增',
    'default' => '',
    'SO' => '=',
  ),
  'city_id' => 
  array (
    'field' => 'city_id',
    'label' => '城市',
    'pk' => false,
    'add' => true,
    'edit' => true,
    'html' => false,
    'empty' => true,
    'show' => true,
    'list' => true,
    'type' => 'city',
    'comment' => '',
    'default' => '',
    'SO' => '=',
  ),
  'shop_id' => 
  array (
    'field' => 'shop_id',
    'label' => '商户',
    'pk' => false,
    'add' => true,
    'edit' => true,
    'html' => false,
    'empty' => true,
    'show' => true,
    'list' => true,
    'type' => 'shop',
    'comment' => '',
    'default' => '',
    'SO' => '=',
  ),
    'user_num' => 
  array (
    'field' => 'user_num',
    'label' => '成团人数',
    'pk' => false,
    'add' => true,
    'edit' => true,
    'html' => false,
    'empty' => true,
    'show' => true,
    'list' => true,
    'type' => 'int',
    'comment' => '成团人数',
    'default' => '',
    'SO' => '=',
  ),
  'master_id' => 
  array (
    'field' => 'master_id',
    'label' => '团长id',
    'pk' => false,
    'add' => true,
    'edit' => true,
    'html' => false,
    'empty' => true,
    'show' => true,
    'list' => true,
    'type' => 'int',
    'comment' => '团长用户id',
    'default' => '',
    'SO' => '=',
  ),
  'start_time' => 
  array (
    'field' => 'start_time',
    'label' => '开团时间',
    'pk' => false,
    'add' => true,
    'edit' => true,
    'html' => false,
    'empty' => true,
    'show' => true,
    'list' => true,
    'type' => 'date',
    'comment' => '开团时间',
    'default' => '',
    'SO' => 'betweendate',
  ),
  'end_time' => 
  array (
    'field' => 'end_time',
    'label' => '结束时间',
    'pk' => false,
    'add' => true,
    'edit' => true,
    'html' => false,
    'empty' => true,
    'show' => true,
    'list' => true,
    'type' => 'date',
    'comment' => '结束时间',
    'default' => '',
    'SO' => 'betweendate',
  ),
  'order_count' => 
  array (
    'field' => 'order_count',
    'label' => '订单数量',
    'pk' => false,
    'add' => true,
    'edit' => true,
    'html' => false,
    'empty' => true,
    'show' => true,
    'list' => true,
    'type' => 'int',
    'comment' => '订单数量',
    'default' => '',
    'SO' => '=',
  ),
  'order_success_count' => 
  array (
    'field' => 'order_success_count',
    'label' => '成功订单数量',
    'pk' => false,
    'add' => true,
    'edit' => true,
    'html' => false,
    'empty' => true,
    'show' => true,
    'list' => true,
    'type' => 'int',
    'comment' => '成功订单数量',
    'default' => '',
    'SO' => false,
  ),
    
    
    'group_title' => 
  array (
    'field' => 'group_title',
    'label' => '拼团名称',
    'pk' => false,
    'add' => true,
    'edit' => true,
    'html' => false,
    'empty' => true,
    'show' => true,
    'list' => true,
    'type' => 'int',
    'comment' => '成功订单数量',
    'default' => '',
    'SO' => false,
  ),
    
    'order_yongjin_count' => 
  array (
    'field' => 'order_yongjin_count',
    'label' => '成功订单数量',
    'pk' => false,
    'add' => true,
    'edit' => true,
    'html' => false,
    'empty' => true,
    'show' => true,
    'list' => true,
    'type' => 'int',
    'comment' => '成功订单数量',
    'default' => '',
    'SO' => false,
  ),
    
  'pintuan_product_id' => 
  array (
    'field' => 'pintuan_product_id',
    'label' => '拼团产品id',
    'pk' => false,
    'add' => true,
    'edit' => true,
    'html' => false,
    'empty' => true,
    'show' => true,
    'list' => true,
    'type' => 'int',
    'comment' => '团产品id',
    'default' => '',
    'SO' => '=',
  ),
  'status' => 
  array (
    'field' => 'status',
    'label' => '组团状态',
    'pk' => false,
    'add' => true,
    'edit' => true,
    'html' => false,
    'empty' => true,
    'show' => true,
    'list' => true,
    'type' => 'radio',
    'comment' => '组团状态  0: 组团中  1:组团成功  2: 组团失败',
    'default' => '',
    'SO' => '=',
  ),
  
  'is_update_price' => 
  array (
    'field' => 'is_update_price',
    'label' => '付款流水',
    'pk' => false,
    'add' => true,
    'edit' => true,
    'html' => false,
    'empty' => true,
    'show' => true,
    'list' => false,
    'type' => 'textarea',
    'comment' => '阶梯团成功,更新订单的价格',
    'default' => '',
    'SO' => false,
  ),
  'clientip' => 
  array (
    'field' => 'clientip',
    'label' => '客户IP',
    'pk' => false,
    'add' => false,
    'edit' => true,
    'html' => false,
    'empty' => true,
    'show' => true,
    'list' => true,
    'type' => 'clientip',
    'comment' => '',
    'default' => '',
    'SO' => false,
  ),
  'dateline' => 
  array (
    'field' => 'dateline',
    'label' => '创建时间',
    'pk' => false,
    'add' => false,
    'edit' => true,
    'html' => false,
    'empty' => true,
    'show' => true,
    'list' => true,
    'type' => 'dateline',
    'comment' => '',
    'default' => '',
    'SO' => false,
  ),
);