<?php
/*
  title =>  显示标题
  ctl       =>  ctl:act
  menu  => 是否显示菜单, 只有有相应权限并且这里设置true才会显示在菜单上
 */
return
    array(
///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
        'index' => array(
            array('title' => '首页','icon' => 'fa fa-home', 'menu' => true,
                'items' => array(
                    array('title' => '管理中心', 'ctl' => 'index:index', 'menu' => true),
                    array('title' => '消息管理', 'ctl' => 'msg:order', 'menu' => true),
                    array('title' => '评价消息', 'ctl' => 'msg:comment', 'nav' => 'msg:order'),
                    array('title' => '投诉消息', 'ctl' => 'msg:complain', 'nav' => 'msg:order'),
                    array('title' => '系统消息', 'ctl' => 'msg:system', 'nav' => 'msg:order'),
                    array('title' => '订单消息详情', 'ctl' => 'order:detailorder', 'menu' => false),
                    array('title' => '评价消息详情', 'ctl' => 'order:detailcomment', 'menu' => false),
                    array('title' => '投诉消息详情', 'ctl' => 'order:detailcomplain', 'menu' => false),
                    array('title' => '系统消息详情', 'ctl' => 'order:detailsystem', 'menu' => false),
                    array('title' => '收入统计', 'ctl' => 'tongji:income', 'menu' => true),
                    array('title' => '收入统计', 'ctl' => 'tongji:w_income', 'nav' => 'tongji:income'),
                    array('title' => '团购、代金券收入统计', 'ctl' => 'tongji:t_income', 'nav' => 'tongji:income'),
                    array('title' => '优惠买单收入统计', 'ctl' => 'tongji:m_income', 'nav' => 'tongji:income'),
                    array('title' => '订单统计', 'ctl' => 'tongji:order', 'menu' => true),
                    array('title' => '外卖订单统计', 'ctl' => 'tongji:w_order', 'nav' => 'tongji:order'),
                    array('title' => '团购订单统计', 'ctl' => 'tongji:t_order', 'nav' => 'tongji:order'),
                    array('title' => '买单订单统计', 'ctl' => 'tongji:m_order', 'nav' => 'tongji:order'),
                    array('title' => '订单来源', 'ctl' => 'tongji:orderfrom', 'menu' => true),
                    array('title' => '团购订单来源', 'ctl' => 'tongji:t_orderfrom', 'nav' => 'tongji:orderfrom'),
                    array('title' => '外卖订单来源', 'ctl' => 'tongji:w_orderfrom', 'nav' => 'tongji:orderfrom'),
                    array('title' => '买单订单来源', 'ctl' => 'tongji:m_orderfrom', 'nav' => 'tongji:orderfrom'),
                    array('title' => '商品销量', 'ctl' => 'tongji:product', 'menu' => true),
                )
            ),
            array('title' => '通用控制器', 'menu' => false,
                'items' => array(
                    array('title' => '上传图片', 'ctl' => 'upload:photo', 'menu' => false),
                    array('title' => '上传图片', 'ctl' => 'upload:editor', 'menu' => false),
                )
            ),
            array('title' => '团购','icon' => 'fa fa-group',  'menu' => true,
                'items' => array(
                    array('title' => '团购管理', 'ctl' => 'tuan/tuan:index', 'menu' => true),
                    array('title' => '添加团购', 'ctl' => 'tuan/tuan:create', 'nav' => 'tuan/tuan:index'),
                    array('title' => '修改团购', 'ctl' => 'tuan/tuan:edit', 'nav' => 'tuan/tuan:index'),
                    array('title' => '删除团购', 'ctl' => 'tuan/tuan:del', 'nav' => 'tuan/tuan:index'),
                    array('title' => '团购商品上架', 'ctl' => 'tuan/tuan:onsale', 'nav' => 'tuan/tuan:index'),
                    array('title' => '搜索团购商品', 'ctl' => 'tuan/tuan:so', 'nav' => 'tuan/tuan:index'),
                    //买单
                    array('title' => '优惠买单', 'ctl' => 'tuan/maidan:index', 'menu' => true),
                    array('title' => '买单订单', 'ctl' => 'tuan/maidan:order', 'menu' => true),
                    array('title' => '删除优惠', 'ctl' => 'tuan/maidan:delete', 'nav' => 'tuan/maidan:index'),
                    //订单
                    array('title' => '订单管理', 'ctl' => 'tuan/order:index', 'menu' => true),
                    array('title' => '待支付', 'ctl' => 'tuan/order:waitpay', 'nav' => 'tuan/order:index'),
                    array('title' => '已取消', 'ctl' => 'tuan/order:cancellist', 'nav' => 'tuan/order:index'),
                    array('title' => '今日完成', 'ctl' => 'tuan/order:todaycomplete', 'nav' => 'tuan/order:index'),
                    array('title' => '总完成', 'ctl' => 'tuan/order:allcomplete', 'nav' => 'tuan/order:index'),
                    array('title' => '团购券管理', 'ctl' => 'tuan/order:ticket', 'menu' => true),
                    array('title' => '团购券核销', 'ctl' => 'tuan/order:used', 'nav' => 'tuan/order:ticket'),
                    array('title' => '团购券验证', 'ctl' => 'tuan/order:dialog', 'nav' => 'tuan/order:ticket'),
                    array('title' => '团购验证', 'ctl' => 'tuan/order:check', 'nav' => 'tuan/order:ticket'),
                    array('title' => '订单详情', 'ctl' => 'tuan/order:detail', 'nav' => 'tuan/order:index'),
                )
            ),
            array('title' => L('微店'),'icon' => 'ico ico1', 'menu' => true,
                'items' => array(
                    array('title' => L('店铺信息'), 'ctl' => 'weidian:index', 'menu' => true),
                    array('title' => L('微店设置'), 'ctl' => 'weidian:open', 'menu' => true),
                    array('title' => L('微店开通'), 'ctl' => 'weidian:open', 'nav' => 'weidian:index'),

                    array('title' => L('广告管理'), 'ctl' => 'weidian/banner:index', 'menu' => true),
                    array('title' => L('创建广告'), 'ctl' => 'weidian/banner:create', 'nav' => 'weidian/banner:index'),
                    array('title' => L('设置状态'), 'ctl' => 'weidian/banner:audit', 'nav' => 'weidian/banner:index'),
                    array('title' => L('修改广告'), 'ctl' => 'weidian/banner:edit', 'nav' => 'weidian/banner:index'),
                    array('title' => L('删除广告'), 'ctl' => 'weidian/banner:delete', 'nav' => 'weidian/banner:index'),
                    array('title' => L('批量删除广告'), 'ctl' => 'weidian/banner:dels', 'nav' => 'weidian/banner:index'),
                    array('title' => L('搜索广告'), 'ctl' => 'weidian/banner:so', 'nav' => 'weidian/banner:index'),
                    array('title' => L('活动列表'), 'ctl' => 'weidian/huodong:index', 'menu' => true),
                    array('title' => L('创建活动'), 'ctl' => 'weidian/huodong:create', 'nav' => 'weidian/huodong:index'),
                    array('title' => L('修改活动'), 'ctl' => 'weidian/huodong:edit', 'nav' => 'weidian/huodong:index'),
                    array('title' => L('删除活动'), 'ctl' => 'weidian/huodong:delete', 'nav' => 'weidian/huodong:index'),
                    array('title' => L('批量删除活动'), 'ctl' => 'weidian/huodong:dels', 'nav' => 'weidian/huodong:index'),
                    array('title' => L('设置活动状态'), 'ctl' => 'weidian/huodong:set_status', 'nav' => 'weidian/huodong:index'),
                    array('title' => L('搜索活动'), 'ctl' => 'weidian/huodong:so', 'nav' => 'weidian/huodong:index'),
                    //优惠券
                    array('title' => '优惠券列表', 'ctl' => 'shop/coupon:index', 'menu' => true),
                    array('title' => '创建优惠券', 'ctl' => 'shop/coupon:create', 'nav' => 'shop/coupon:create'),
                    array('title' => '修改优惠券', 'ctl' => 'shop/coupon:edit', 'nav' => 'shop/coupon:edit'),
                    array('title' => '删除优惠券', 'ctl' => 'shop/coupon:delete', 'nav' => 'shop/coupon:delete'),
                    array('title' => '搜索优惠券', 'ctl' => 'shop/coupon:so', 'nav' => 'shop/coupon:index'),
                    //商品
                    array('title' => L('商品分类'), 'ctl' => 'weidian/productcate:index', 'menu' => true),
                    array('title' => L('添加分类'), 'ctl' => 'weidian/productcate:create', 'nav' => 'weidian/productcate:index'),
                    array('title' => L('修改分类'), 'ctl' => 'weidian/productcate:edit', 'nav' => 'weidian/productcate:index'),
                    array('title' => L('删除分类'), 'ctl' => 'weidian/productcate:delete', 'nav' => 'weidian/productcate:index'),
                    array('title' => L('更新分类'), 'ctl' => 'weidian/productcate:update', 'nav' => 'weidian/productcate:index'),
                    array('title' => L('更新分类'), 'ctl' => 'weidian/productcate:example', 'nav' => 'weidian/productcate:index'),

                    array('title' => L('普通商品'), 'ctl' => 'weidian/product:index', 'menu' => true),
                    array('title' => L('添加商品'), 'ctl' => 'weidian/product:create', 'nav' => 'weidian/product:index'),
                    array('title' => L('修改商品'), 'ctl' => 'weidian/product:edit', 'nav' => 'weidian/product:index'),
                    array('title' => L('搜索商品'), 'ctl' => 'weidian/product:so', 'nav' => 'weidian/product:index'),
                    array('title' => L('删除商品'), 'ctl' => 'weidian/product:delete', 'nav' => 'weidian/product:index'),
                    array('title' => L('更新商品'), 'ctl' => 'weidian/product:open', 'nav' => 'weidian/product:index'),
                    array('title' => L('上架商品'), 'ctl' => 'weidian/product:onsale_open', 'nav' => 'weidian/product:index'),
                    array('title' => L('上架商品'), 'ctl' => 'weidian/product:onsale_openall', 'nav' => 'weidian/product:index'),
                    array('title' => L('下架商品'), 'ctl' => 'weidian/product:onsale_close', 'nav' => 'weidian/product:index'),
                    array('title' => L('设置规格名称'), 'ctl' => 'weidian/product:set_name', 'nav' => 'weidian/product:index'),
                    array('title' => L('设置规格属性'), 'ctl' => 'weidian/product:set_value', 'nav' => 'weidian/product:index'),
                    array('title' => L('设置规格属性'), 'ctl' => 'weidian/product:get_attr', 'nav' => 'weidian/product:index'),
                    array('title' => L('设置是否开放分销'), 'ctl' => 'weidian/product:set_is_fenxiao', 'nav' => 'weidian/product:index'),
                    //订单
                    array('title' => L('商品订单'), 'ctl' => 'weidian/order:index', 'menu' => true),
                    array('title' => L('待确认'), 'ctl' => 'weidian/order:wait', 'nav' => 'weidian/order:index'),
                    array('title' => L('待发货'), 'ctl' => 'weidian/order:fahuo', 'nav' => 'weidian/order:index'),
                    array('title' => L('待收货'), 'ctl' => 'weidian/order:shouhuo', 'nav' => 'weidian/order:index'),
                    array('title' => L('已收货'), 'ctl' => 'weidian/order:confirm', 'nav' => 'weidian/order:index'),
                    array('title' => L('已完成'), 'ctl' => 'weidian/order:complete', 'nav' => 'weidian/order:index'),
                    array('title' => L('已取消'), 'ctl' => 'weidian/order:cancellist', 'nav' => 'weidian/order:index'),
                    array('title' => L('自提单'), 'ctl' => 'weidian/order:ziti', 'nav' => 'weidian/order:index'),
                    array('title' => '接单按钮', 'ctl' => 'weidian/order:accept', 'nav' => 'weidian/order:index'),
                    array('title' => '发货按钮', 'ctl' => 'weidian/order:sendgoods', 'nav' => 'weidian/order:index'),
                    array('title' => '确认收货按钮', 'ctl' => 'weidian/order:service', 'nav' => 'weidian/order:index'),
                    array('title' => '确认完成按钮', 'ctl' => 'weidian/order:finish', 'nav' => 'weidian/order:index'),
                    array('title' => '核销按钮', 'ctl' => 'weidian/order:dialog', 'nav' => 'weidian/order:index'),
                    array('title' => '核销按钮', 'ctl' => 'weidian/order:setspend', 'nav' => 'weidian/order:index'),
                    array('title' => '取消订单', 'ctl' => 'weidian/order:cancel', 'nav' => 'weidian/order:index'),
                    array('title' => '订单评价', 'ctl' => 'weidian/comment:comment', 'menu' => true),
                    array('title' => '未回复的订单评价', 'ctl' => 'weidian/comment:comment_wait', 'nav' => 'weidian/comment:comment'),
                    array('title' => '回复订单评价', 'ctl' => 'weidian/comment:reply', 'nav' => 'weidian/comment:comment'),
                    array('title' => '订单评价详情', 'ctl' => 'weidian/comment:detail', 'nav' => 'weidian/comment:comment'),
                )
            ),
            array('title' => L('拼团'),'icon' => 'ico ico2','menu' => true,
                'items' => array(
                    array('title' => L('拼团商品'), 'ctl' => 'weidian/pintuanproduct:index', 'menu' => true),
                    array('title' => L('添加拼团商品'), 'ctl' => 'weidian/pintuanproduct:create', 'nav' => 'weidian/pintuanproduct:index'),
                    array('title' => L('修改拼团商品'), 'ctl' => 'weidian/pintuanproduct:edit', 'nav' => 'weidian/pintuanproduct:index'),
                    array('title' => L('修改拼团商品'), 'ctl' => 'weidian/pintuanproduct:so', 'nav' => 'weidian/pintuanproduct:index'),
                    array('title' => L('删除拼团商品'), 'ctl' => 'weidian/pintuanproduct:delete', 'nav' => 'weidian/pintuanproduct:index'),
                    array('title' => L('更新拼团商品'), 'ctl' => 'weidian/pintuanproduct:update', 'nav' => 'weidian/pintuanproduct:index'),
                    array('title' => L('设置规格名称'), 'ctl' => 'weidian/pintuanproduct:set_name', 'nav' => 'weidian/pintuanproduct:index'),
                    array('title' => L('设置规格属性'), 'ctl' => 'weidian/pintuanproduct:set_value', 'nav' => 'weidian/pintuanproduct:index'),
                    array('title' => L('设置规格属性'), 'ctl' => 'weidian/pintuanproduct:get_attr', 'nav' => 'weidian/pintuanproduct:index'),
                    array('title' => L('拼团管理'), 'ctl' => 'weidian/pintuangroup:index', 'menu' => true),
                    array('title' => L('更新拼团'), 'ctl' => 'weidian/pintuangroup:update', 'nav' => 'weidian/pintuangroup:index'),
                    array('title' => L('查看拼团'), 'ctl' => 'weidian/pintuangroup:detail', 'nav' => 'weidian/pintuangroup:index'),
                    array('title' => L('组团中-拼团'), 'ctl' => 'weidian/pintuangroup:start', 'nav' => 'weidian/pintuangroup:index'),
                    array('title' => L('组团成功-拼团'), 'ctl' => 'weidian/pintuangroup:process', 'nav' => 'weidian/pintuangroup:index'),
                    array('title' => L('组团失败-拼团'), 'ctl' => 'weidian/pintuangroup:complete', 'nav' => 'weidian/pintuangroup:index'),
                    array('title' => L('商家已接单-拼团'), 'ctl' => 'weidian/pintuangroup:ok', 'nav' => 'weidian/pintuangroup:index'),
                    array('title' => L('商家接单-拼团'), 'ctl' => 'weidian/pintuangroup:status_ok', 'nav' => 'weidian/pintuangroup:index'),
                    array('title' => L('商家取消组团-拼团'), 'ctl' => 'weidian/pintuangroup:status_complete', 'nav' => 'weidian/pintuangroup:index'),

                    array('title' => L('拼团订单管理'), 'ctl' => 'weidian/pintuanorder:index', 'menu' => true),
                    array('title' => L('配送订单'), 'ctl' => 'weidian/pintuanorder:pei', 'nav' => 'weidian/pintuanorder:index'),
                    array('title' => L('配送完成'), 'ctl' => 'weidian/pintuanorder:delivered', 'nav' => 'weidian/pintuanorder:index'),
                    array('title' => L('订单完成'), 'ctl' => 'weidian/pintuanorder:complete', 'nav' => 'weidian/pintuanorder:index'),
                    array('title' => L('取消订单'), 'ctl' => 'weidian/pintuanorder:cancellist', 'nav' => 'weidian/pintuanorder:index'),
                    array('title' => L('配送订单'), 'ctl' => 'weidian/pintuanorder:pei', 'nav' => 'weidian/pintuanorder:index'),

                    array('title' => L('拼团佣金记录'), 'ctl' => 'weidian/pintuanyongjin:index', 'menu' => true),
                    array('title' => L('支付佣金'), 'ctl' => 'weidian/pintuanyongjin:pay', 'nav' => 'weidian/pintuanyongjin:index'),
                    array('title' => L('查看流水'), 'ctl' => 'weidian/pintuanyongjin:log', 'nav' => 'weidian/pintuanyongjin:index'),
                )
            ),
            array('title' => L('分销'),'icon' => 'fa fa-sitemap', 'menu' => true,
                'items' => array(
                    array('title' => L('分销设置'), 'ctl' => 'weidian/fenxiao:index', 'menu' => true),
                    array('title' => L('店铺列表'), 'ctl' => 'weidian/fenxiao:items', 'menu' => true),
                    array('title' => L('分销商品'), 'ctl' => 'weidian/fenxiao:product', 'menu' => true),
                    array('title' => L('分销订单'), 'ctl' => 'weidian/fenxiao:orders', 'menu' => true),
                    array('title' => L('分销待发货订单'), 'ctl' => 'weidian/fenxiao:f_fahuo', 'nav' => 'weidian/fenxiao:orders'),
                    array('title' => L('分销待收货订单'), 'ctl' => 'weidian/fenxiao:f_shouhuo', 'nav' => 'weidian/fenxiao:orders'),
                    array('title' => L('分销已收货订单'), 'ctl' => 'weidian/fenxiao:f_confirm', 'nav' => 'weidian/fenxiao:orders'),
                    array('title' => L('分销已完成订单'), 'ctl' => 'weidian/fenxiao:f_complete', 'nav' => 'weidian/fenxiao:orders'),
                    array('title' => L('分销已取消订单'), 'ctl' => 'weidian/fenxiao:f_cancellist', 'nav' => 'weidian/fenxiao:orders'),
                    array('title' => L('分销自提订单'), 'ctl' => 'weidian/fenxiao:f_ziti', 'nav' => 'weidian/fenxiao:orders'),
                    array('title' => L('设置状态'), 'ctl' => 'weidian/fenxiao:set_status', 'nav' => 'weidian/fenxiao:orders'),

                )
            ),
            array('title' => '外送', 'icon' => 'fa fa-motorcycle','menu' => true,
                'items' => array(
                    array('title' => '商品管理', 'ctl' => 'waimai/product:index', 'menu' => true),
                    array('title' => '分类管理', 'ctl' => 'waimai/cate:index', 'menu' => true),
                    array('title' => '商品管理', 'ctl' => 'waimai/product:skunotice', 'nav' => 'waimai/product:index'),
                    array('title' => '库存管理', 'ctl' => 'waimai/product:stock_add', 'nav' => 'waimai/product:index'),
                    array('title' => '上架产品', 'ctl' => 'waimai/product:onsale_open', 'nav' => 'waimai/product:index'),
                    array('title' => '下架产品', 'ctl' => 'waimai/product:onsale_close', 'nav' => 'waimai/product:index'),
                    array('title' => '创建分类', 'ctl' => 'waimai/cate:create', 'nav' => 'waimai/cate:index'),
                    array('title' => '修改分类', 'ctl' => 'waimai/cate:edit', 'nav' => 'waimai/cate:index'),
                    array('title' => '删除分类', 'ctl' => 'waimai/cate:delete', 'nav' => 'waimai/cate:index'),
                    array('title' => '创建商品', 'ctl' => 'waimai/product:create', 'nav' => 'waimai/product:index'),
                    array('title' => '修改商品', 'ctl' => 'waimai/product:edit', 'nav' => 'waimai/product:index'),
                    array('title' => '删除商品', 'ctl' => 'waimai/product:delete', 'nav' => 'waimai/product:index'),
                    array('title' => '商品规格', 'ctl' => 'waimai/product:specs', 'nav' => 'waimai/product:index'),
                    array('title' => '删除规格', 'ctl' => 'waimai/product:specs_del', 'nav' => 'waimai/product:index'),
                    array('title' => '上架状态设置', 'ctl' => 'waimai/product:open', 'nav' => 'waimai/product:index'),
                    //array('title' => '快速管理', 'ctl' => 'waimai/ordermanage:index', 'menu' => false),
                    array('title' => '外送订单', 'ctl' => 'waimai/order:index', 'menu' => true),
                    array('title' => '外送订单', 'ctl' => 'waimai/order:waimai', 'nav' => 'waimai/order:index'),
                    array('title' => '修改配送方式', 'ctl' => 'waimai/order:setpei', 'nav' => 'waimai/order:index'),
                    array('title' => '配送订单', 'ctl' => 'waimai/order:pei', 'nav' => 'waimai/order:index'),
                    array('title' => '配送完成订单', 'ctl' => 'waimai/order:delivered', 'nav' => 'waimai/order:index'),
                    array('title' => '完成的订单', 'ctl' => 'waimai/order:complete', 'nav' => 'waimai/order:index'),
                    array('title' => '取消的订单', 'ctl' => 'waimai/order:cancellist', 'nav' => 'waimai/order:index'),
                    array('title' => '自提订单', 'ctl' => 'waimai/order:ziti', 'nav' => 'waimai/order:index'),
                    array('title' => '配送按钮', 'ctl' => 'waimai/order:peisong', 'nav' => 'waimai/order:index'),
                    array('title' => '取消订单按钮', 'ctl' => 'waimai/order:cancel', 'nav' => 'waimai/order:index'),
                    array('title' => '完成订单按钮', 'ctl' => 'waimai/order:finish', 'nav' => 'waimai/order:index'),
                    array('title' => '接单按钮', 'ctl' => 'waimai/order:accept', 'nav' => 'waimai/order:index'),
                    array('title' => '订单详情', 'ctl' => 'waimai/order:detail', 'nav' => 'waimai/order:index'),
                    array('title' => '自提订单核销', 'ctl' => 'waimai/order:setspend', 'nav' => 'waimai/order:index'),
                    array('title' => '堂食订单核销', 'ctl' => 'waimai/order:setspendEatin', 'nav' => 'waimai/order:index'),
                    array('title' => '订单核销弹框', 'ctl' => 'waimai/order:dialog', 'nav' => 'waimai/order:index'),
                    array('title' => '打印小票', 'ctl' => 'waimai/order:porder', 'nav' => 'waimai/order:index'),
                    array('title' => '检查打印平台', 'ctl' => 'waimai/order:check_print', 'nav' => 'waimai/order:index'),
                    array('title' => '在线云打印', 'ctl' => 'waimai/order:yun_print', 'nav' => 'waimai/order:index'),
                    array('title' => '店铺设置', 'ctl' => 'waimai:index', 'menu' => true),
                    array('title' => '配送设置', 'ctl' => 'waimai/shop:pei', 'menu' => true),
                    array('title' => '店铺设置', 'ctl' => 'waimai/shop:have', 'menu' => false),
                    array('title' => '优惠设置', 'ctl' => 'waimai/shop:youhui', 'menu' => true),
                    array('title' => '删除优惠', 'ctl' => 'waimai/shop:yhdelete', 'nav' => 'waimai/shop:youhui'),
                    array('title' => '搜索', 'ctl' => 'waimai/order:so', 'nav' => 'waimai/order:so'),
                )
            ),
            array('title' => '预约','icon' => 'fa fa-phone', 'menu' => true,
                'items' => array(
                    array('title' => '桌号管理', 'ctl' => 'yuyue/zhuohao:items', 'menu' => true),
                    array('title' => '分类管理', 'ctl' => 'yuyue/zhuohao:cate', 'menu' => true),
                    array('title' => '打印桌号', 'ctl' => 'yuyue/qrcode:items', 'menu' => true),
                    array('title' => '添加桌号分类', 'ctl' => 'yuyue/zhuohao:cate_create', 'nav' => 'yuyue/zhuohao:cate'),
                    array('title' => '修改桌号分类', 'ctl' => 'yuyue/zhuohao:cate_edit', 'nav' => 'yuyue/zhuohao:cate'),
                    array('title' => '删除桌号分类', 'ctl' => 'yuyue/zhuohao:cate_delete', 'nav' => 'yuyue/zhuohao:cate'),
                    array('title' => '添加桌号', 'ctl' => 'yuyue/zhuohao:zhuohao_create', 'nav' => 'yuyue/zhuohao:items'),
                    array('title' => '修改桌号', 'ctl' => 'yuyue/zhuohao:zhuohao_edit', 'nav' => 'yuyue/zhuohao:items'),
                    array('title' => '删除桌号', 'ctl' => 'yuyue/zhuohao:zhuohao_delete', 'nav' => 'yuyue/zhuohao:items'),
                    array('title' => '搜索桌号', 'ctl' => 'yuyue/zhuohao:so', 'nav' => 'yuyue/zhuohao:items'),
                    array('title' => '排号订单', 'ctl' => 'yuyue/order:paidui', 'menu' => true),
                    array('title' => '订座订单', 'ctl' => 'yuyue/order:dingzuo', 'menu' => true),
                    array('title' => '排号订单选择桌号', 'ctl' => 'yuyue/order:paidui_choose_zhuohao', 'nav' => 'yuyue/order:paidui'),
                    array('title' => '订座订单选择桌号', 'ctl' => 'yuyue/order:dingzuo_choose_zhuohao', 'nav' => 'yuyue/order:dingzuo'),
                    array('title' => '排号订单接单', 'ctl' => 'yuyue/order:paidui_jiedan', 'nav' => 'yuyue/order:paidui'),
                    array('title' => '排号订单取消', 'ctl' => 'yuyue/order:paidui_cancel', 'nav' => 'yuyue/order:paidui'),
                    array('title' => '排号订单完成', 'ctl' => 'yuyue/order:paidui_complete', 'nav' => 'yuyue/order:paidui'),
                    array('title' => '排号订单删除', 'ctl' => 'yuyue/order:paidui_delete', 'nav' => 'yuyue/order:paidui'),

                    array('title' => '排号订单排队中列表', 'ctl' => 'yuyue/order:paidui_wait_items', 'nav' => 'yuyue/order:paidui'),
                    array('title' => '排号订单已完成列表', 'ctl' => 'yuyue/order:paidui_complete_items', 'nav' => 'yuyue/order:paidui'),
                    array('title' => '排号订单已取消列表', 'ctl' => 'yuyue/order:paidui_cancel_items', 'nav' => 'yuyue/order:paidui'),

                    array('title' => '订座订单接单', 'ctl' => 'yuyue/order:dingzuo_jiedan', 'nav' => 'yuyue/order:dingzuo'),
                    array('title' => '订座订单取消', 'ctl' => 'yuyue/order:dingzuo_cancel', 'nav' => 'yuyue/order:dingzuo'),
                    array('title' => '订座订单完成', 'ctl' => 'yuyue/order:dingzuo_complete', 'nav' => 'yuyue/order:dingzuo'),
                    array('title' => '订座订单删除', 'ctl' => 'yuyue/order:dingzuo_delete', 'nav' => 'yuyue/order:dingzuo'),

                    array('title' => '订座订单排队中列表', 'ctl' => 'yuyue/order:dingzuo_wait_items', 'nav' => 'yuyue/order:dingzuo'),
                    array('title' => '订座订单已完成列表', 'ctl' => 'yuyue/order:dingzuo_complete_items', 'nav' => 'yuyue/order:dingzuo'),
                    array('title' => '订座订单已取消列表', 'ctl' => 'yuyue/order:dingzuo_cancel_items', 'nav' => 'yuyue/order:dingzuo'),
                )
            ),
            array('title' => L('微信'),'icon' => 'fa fa-weixin','menu' => true,
                'items' => array(
                    array('title' => L('微信管理'), 'ctl' => 'weixin/index:index', 'nav' => 'weixin/index:index', 'menu' => true),
                    array('title' => L('绑定'), 'ctl' => 'weixin/index:bind', 'nav' => 'weixin/index:index'),
                    array('title' => L('绑定公众号'), 'ctl' => 'weixin/index:wxloginpage', 'nav' => 'weixin/index:index'),
                    array('title' => L('绑定公众号'), 'ctl' => 'weixin/index:wxcallback', 'nav' => 'weixin/index:index'),
                    array('title' => L('单次关注'), 'ctl' => 'weixin/index:welcome', 'nav' => 'weixin/index:welcome', 'menu' => true),
                    array('title' => L('自动回复'), 'ctl' => 'weixin/index:auto', 'nav' => 'weixin:index', 'menu' => true),
                    array('title' => L('关键字回复'), 'ctl' => 'weixin/keyword:index', 'nav' => 'weixin/keyword:index', 'menu' => true),
                    array('title' => L('添加关键字'), 'ctl' => 'weixin/keyword:create', 'nav' => 'weixin/keyword:index'),
                    array('title' => L('修改关键字'), 'ctl' => 'weixin/keyword:edit', 'nav' => 'weixin/keyword:index'),
                    array('title' => L('删除关键字'), 'ctl' => 'weixin/keyword:delete', 'nav' => 'weixin/keyword:index'),
                    array('title' => L('自定义菜单'), 'ctl' => 'weixin/menu:index', 'nav' => 'weixin/menu:index', 'menu' => true),
                    array('title' => L('添加菜单'), 'ctl' => 'weixin/menu:create', 'nav' => 'weixin/menu:index'),
                    array('title' => L('修改菜单'), 'ctl' => 'weixin/menu:edit', 'nav' => 'weixin/menu:index'),
                    array('title' => L('删除菜单'), 'ctl' => 'weixin/menu:delete', 'nav' => 'weixin/menu:index'),
                    array('title' => L('同步菜单'), 'ctl' => 'weixin/menu:towechat', 'nav' => 'weixin/menu:index'),
                    array('title' => L('微信素材'), 'ctl' => 'weixin/reply:index', 'menu' => true),
                    array('title' => L('添加素材'), 'ctl' => 'weixin/reply:create', 'nav' => 'weixin/reply:index'),
                    array('title' => L('修改素材'), 'ctl' => 'weixin/reply:edit', 'nav' => 'weixin/reply:index'),
                    array('title' => L('删除素材'), 'ctl' => 'weixin/reply:delete', 'nav' => 'weixin/reply:index'),
                    array('title' => L('选择素材'), 'ctl' => 'weixin/reply:dialog', 'nav' => 'weixin/reply:index'),
                    //优惠券
                    array('title' => L('优惠券'), 'ctl' => 'weixin/coupon:index', 'nav' => 'weixin/coupon:index', 'menu' => true),
                    array('title' => L('添加优惠券'), 'ctl' => 'weixin/coupon:create', 'nav' => 'weixin/coupon:index'),
                    array('title' => L('修改优惠券'), 'ctl' => 'weixin/coupon:edit', 'nav' => 'weixin/coupon:index'),
                    array('title' => L('删除优惠券'), 'ctl' => 'weixin/coupon:delete', 'nav' => 'weixin/coupon:index'),
                    array('title' => L('领取优惠券'), 'ctl' => 'weixin/coupon:sign', 'nav' => 'weixin/coupon:index'),
                    array('title' => L('优惠码'), 'ctl' => 'weixin/coupon:sn', 'nav' => 'weixin/coupon:index'),
                    array('title' => L('预览'), 'ctl' => 'weixin/coupon:preview', 'nav' => 'weixin/coupon:index'),
                    array('title' => L('改变状态'), 'ctl' => 'weixin/coupon:snedit', 'nav' => 'weixin/coupon:index'),
                    array('title' => L('删除成员'), 'ctl' => 'weixin/coupon:sndelete', 'nav' => 'weixin/coupon:index'),

                    //刮刮卡
                    array('title' => L('刮刮卡'), 'ctl' => 'weixin/scratch:index', 'nav' => 'weixin/scratch:index', ),
                    array('title' => L('添加刮刮卡'), 'ctl' => 'weixin/scratch:create', 'nav' => 'weixin/scratch:index'),
                    array('title' => L('修改刮刮卡'), 'ctl' => 'weixin/scratch:edit', 'nav' => 'weixin/scratch:index'),
                    array('title' => L('删除刮刮卡'), 'ctl' => 'weixin/scratch:delete', 'nav' => 'weixin/scratch:index'),
                    array('title' => L('领取优惠券'), 'ctl' => 'weixin/scratch:sign', 'nav' => 'weixin/scratch:index'),
                    array('title' => L('中奖用户'), 'ctl' => 'weixin/scratch:sn', 'nav' => 'weixin/scratch:index'),
                    array('title' => L('删除用户'), 'ctl' => 'weixin/scratch:sndelete', 'nav' => 'weixin/scratch:index'),
                    array('title' => L('改变状态'), 'ctl' => 'weixin/scratch:snedit', 'nav' => 'weixin/scratch:index'),
                    array('title' => L('预览'), 'ctl' => 'weixin/scratch:preview', 'nav' => 'weixin/scratch:index'),
                    array('title' => L('奖品'), 'ctl' => 'weixin/scratch:goods', 'nav' => 'weixin/scratch:index'),
                    array('title' => L('添加奖品'), 'ctl' => 'weixin/scratch:goodscreate', 'nav' => 'weixin/scratch:index'),
                    array('title' => L('修改奖品'), 'ctl' => 'weixin/scratch:goodsedit', 'nav' => 'weixin/scratch:index'),
                    array('title' => L('删除奖品'), 'ctl' => 'weixin/scratch:goodsdelete', 'nav' => 'weixin/scratch:index'),

                    //大转盘
                    array('title' => L('大转盘'), 'ctl' => 'weixin/lottery:index', 'nav' => 'weixin/lottery:index', ),
                    array('title' => L('添加大转盘'), 'ctl' => 'weixin/lottery:create', 'nav' => 'weixin/lottery:index'),
                    array('title' => L('修改大转盘'), 'ctl' => 'weixin/lottery:edit', 'nav' => 'weixin/lottery:index'),
                    array('title' => L('删除大转盘'), 'ctl' => 'weixin/lottery:delete', 'nav' => 'weixin/lottery:index'),
                    array('title' => L('中奖用户'), 'ctl' => 'weixin/lottery:sn', 'nav' => 'weixin/lottery:index'),
                    array('title' => L('删除用户'), 'ctl' => 'weixin/lottery:sndelete', 'nav' => 'weixin/lottery:index'),
                    array('title' => L('改变状态'), 'ctl' => 'weixin/lottery:snedit', 'nav' => 'weixin/lottery:index'),
                    array('title' => L('预览'), 'ctl' => 'weixin/lottery:preview', 'nav' => 'weixin/lottery:index'),

                    //砸金蛋
                    array('title' => L('砸金蛋'), 'ctl' => 'weixin/goldegg:index', 'nav' => 'weixin/goldegg:index', ),
                    array('title' => L('添加砸金蛋'), 'ctl' => 'weixin/goldegg:create', 'nav' => 'weixin/goldegg:index'),
                    array('title' => L('修改砸金蛋'), 'ctl' => 'weixin/goldegg:edit', 'nav' => 'weixin/goldegg:index'),
                    array('title' => L('删除砸金蛋'), 'ctl' => 'weixin/goldegg:delete', 'nav' => 'weixin/goldegg:index'),
                    array('title' => L('中奖用户'), 'ctl' => 'weixin/goldegg:sn', 'nav' => 'weixin/goldegg:index'),
                    array('title' => L('删除用户'), 'ctl' => 'weixin/goldegg:sndelete', 'nav' => 'weixin/goldegg:index'),
                    array('title' => L('改变状态'), 'ctl' => 'weixin/goldegg:snedit', 'nav' => 'weixin/goldegg:index'),
                    array('title' => L('预览'), 'ctl' => 'weixin/goldegg:preview', 'nav' => 'weixin/goldegg:index'),

                    //红包
                    array('title' => L('抢红包'), 'ctl' => 'weixin/packet:index', 'nav' => 'weixin/packet:index',),
                    array('title' => L('添加红包'), 'ctl' => 'weixin/packet:create', 'nav' => 'weixin/packet:index'),
                    array('title' => L('修改红包'), 'ctl' => 'weixin/packet:edit', 'nav' => 'weixin/packet:index'),
                    array('title' => L('删除红包'), 'ctl' => 'weixin/packet:delete', 'nav' => 'weixin/packet:index'),
                    array('title' => L('兑换'), 'ctl' => 'weixin/packet:logs', 'nav' => 'weixin/packet:index'),
                    array('title' => L('中奖用户'), 'ctl' => 'weixin/packet:sn', 'nav' => 'weixin/packet:index'),
                    array('title' => L('删除用户'), 'ctl' => 'weixin/packet:sndelete', 'nav' => 'weixin/packet:index'),
                    array('title' => L('改变状态'), 'ctl' => 'weixin/packet:snedit', 'nav' => 'weixin/packet:index'),
                    array('title' => L('预览'), 'ctl' => 'weixin/packet:preview', 'nav' => 'weixin/packet:index'),

                    //卡券
                    /*
                    array('title'=>L('卡券'), 'ctl'=>'weixin/card:index','nav'=>'weixin/card:index','menu'=>true),
                    array('title'=>L('添加卡券'), 'ctl'=>'weixin/card:create', 'nav'=>'weixin/card:index'),
                    array('title'=>L('修改卡券'), 'ctl'=>'weixin/card:edit', 'nav'=>'weixin/card:index'),
                    array('title'=>L('删除卡券'), 'ctl'=>'weixin/card:delete', 'nav'=>'weixin/card:index'),
                    array('title'=>L('中奖用户'), 'ctl'=>'weixin/card:sn', 'nav'=>'weixin/card:index'),
                    array('title'=>L('删除用户'), 'ctl'=>'weixin/card:sndelete', 'nav'=>'weixin/card:index'),
                    array('title'=>L('改变状态'), 'ctl'=>'weixin/card:snedit', 'nav'=>'weixin/card:index'),
                    array('title'=>L('预览'), 'ctl'=>'weixin/card:preview', 'nav'=>'weixin/card:index'),
                    */
                    //摇一摇
                    array('title' => L('摇一摇'), 'ctl' => 'weixin/shake:index', 'nav' => 'weixin/shake:index', ),
                    array('title' => L('添加摇一摇'), 'ctl' => 'weixin/shake:create', 'nav' => 'weixin/shake:index'),
                    array('title' => L('修改摇一摇'), 'ctl' => 'weixin/shake:edit', 'nav' => 'weixin/shake:index'),
                    array('title' => L('删除摇一摇'), 'ctl' => 'weixin/shake:delete', 'nav' => 'weixin/shake:index'),
                    array('title' => L('领取优惠券'), 'ctl' => 'weixin/shake:sign', 'nav' => 'weixin/shake:index'),
                    array('title' => L('中奖用户'), 'ctl' => 'weixin/shake:sn', 'nav' => 'weixin/shake:index'),
                    array('title' => L('删除用户'), 'ctl' => 'weixin/shake:sndelete', 'nav' => 'weixin/shake:index'),
                    array('title' => L('改变状态'), 'ctl' => 'weixin/shake:snedit', 'nav' => 'weixin/shake:index'),
                    array('title' => L('预览'), 'ctl' => 'weixin/shake:preview', 'nav' => 'weixin/shake:index'),
                    array('title' => L('奖品'), 'ctl' => 'weixin/shake:goods', 'nav' => 'weixin/shake:index'),
                    array('title' => L('添加奖品'), 'ctl' => 'weixin/shake:goodscreate', 'nav' => 'weixin/shake:index'),
                    array('title' => L('修改奖品'), 'ctl' => 'weixin/shake:goodsedit', 'nav' => 'weixin/shake:index'),
                    array('title' => L('删除奖品'), 'ctl' => 'weixin/shake:goodsdelete', 'nav' => 'weixin/shake:index'),

                    //微助力
                    array('title' => L('微助力'), 'ctl' => 'weixin/help:index', 'nav' => 'weixin/help:index', ),
                    array('title' => L('添加微助力'), 'ctl' => 'weixin/help:create', 'nav' => 'weixin/help:index'),
                    array('title' => L('修改微助力'), 'ctl' => 'weixin/help:edit', 'nav' => 'weixin/help:index'),
                    array('title' => L('删除微助力'), 'ctl' => 'weixin/help:delete', 'nav' => 'weixin/help:index'),
                    array('title' => L('领取优惠券'), 'ctl' => 'weixin/help:sign', 'nav' => 'weixin/help:index'),
                    array('title' => L('中奖用户'), 'ctl' => 'weixin/help:sn', 'nav' => 'weixin/help:index'),
                    array('title' => L('删除用户'), 'ctl' => 'weixin/help:sndelete', 'nav' => 'weixin/help:index'),
                    array('title' => L('改变状态'), 'ctl' => 'weixin/help:snedit', 'nav' => 'weixin/help:index'),
                    array('title' => L('预览'), 'ctl' => 'weixin/help:preview', 'nav' => 'weixin/help:index'),
                    array('title' => L('奖品'), 'ctl' => 'weixin/help:goods', 'nav' => 'weixin/help:index'),
                    array('title' => L('添加奖品'), 'ctl' => 'weixin/help:goodscreate', 'nav' => 'weixin/help:index'),
                    array('title' => L('修改奖品'), 'ctl' => 'weixin/help:goodsedit', 'nav' => 'weixin/help:index'),
                    array('title' => L('删除奖品'), 'ctl' => 'weixin/help:goodsdelete', 'nav' => 'weixin/help:index'),

                    //微接力
                    array('title' => L('微接力'), 'ctl' => 'weixin/relay:index', 'nav' => 'weixin/relay:index', ),
                    array('title' => L('添加微接力'), 'ctl' => 'weixin/relay:create', 'nav' => 'weixin/relay:index'),
                    array('title' => L('修改微接力'), 'ctl' => 'weixin/relay:edit', 'nav' => 'weixin/relay:index'),
                    array('title' => L('删除微接力'), 'ctl' => 'weixin/relay:delete', 'nav' => 'weixin/relay:index'),
                    array('title' => L('领取优惠券'), 'ctl' => 'weixin/relay:sign', 'nav' => 'weixin/relay:index'),
                    array('title' => L('中奖用户'), 'ctl' => 'weixin/relay:sn', 'nav' => 'weixin/relay:index'),
                    array('title' => L('删除用户'), 'ctl' => 'weixin/relay:sndelete', 'nav' => 'weixin/relay:index'),
                    array('title' => L('改变状态'), 'ctl' => 'weixin/relay:snedit', 'nav' => 'weixin/relay:index'),
                    array('title' => L('预览'), 'ctl' => 'weixin/relay:preview', 'nav' => 'weixin/relay:index'),
                    array('title' => L('奖品'), 'ctl' => 'weixin/relay:goods', 'nav' => 'weixin/relay:index'),
                    array('title' => L('添加奖品'), 'ctl' => 'weixin/relay:goodscreate', 'nav' => 'weixin/relay:index'),
                    array('title' => L('修改奖品'), 'ctl' => 'weixin/relay:goodsedit', 'nav' => 'weixin/relay:index'),
                    array('title' => L('删除奖品'), 'ctl' => 'weixin/relay:goodsdelete', 'nav' => 'weixin/relay:index'),
                )
            ),
            array('title' => '店铺','icon' => 'fa fa-institution', 'menu' => true,
                'items' => array(
                    array('title' => '店铺首页', 'ctl' => 'shop:see', 'menu' => true),
                    array('title' => '资料设置', 'ctl' => 'shop:index', 'menu' => true),
                    array('title' => '安全设置', 'ctl' => 'shop:passwd', 'nav' => 'shop:index'),
                    array('title' => '获取商圈', 'ctl' => 'shop:get_business', 'nav' => 'shop:index'),
                    array('title' => '更换手机', 'ctl' => 'shop:mobile', 'nav' => 'shop:index'),
                    array('title' => '提现帐号', 'ctl' => 'shop:account', 'nav' => 'shop:index'),
                    array('title' => '店铺认证', 'ctl' => 'shop/verify:index', 'menu' => true),
                    array('title' => '店主认证', 'ctl' => 'shop/verify:dianzhu', 'nav' => 'shop/verify:index'),
                    array('title' => '企业认证', 'ctl' => 'shop/verify:yyzz', 'nav' => 'shop/verify:index'),
                    array('title' => '餐饮认证', 'ctl' => 'shop/verify:canyin', 'nav' => 'shop/verify:index'),
                    array('title' => '功能开通', 'ctl' => 'shop/open:index', 'menu' => true),
                    array('title' => '功能开通', 'ctl' => 'shop/open:save', 'nav' => 'shop/open:save'),
                    array('title' => '打印设置', 'ctl' => 'shop/print:index', 'menu' => true),
                    array('title' => '添加设置', 'ctl' => 'shop/print:create', 'nav' => 'shop/print:index'),
                    array('title' => '相册设置', 'ctl' => 'shop/album:index', 'menu' => true),
                    array('title' => '添加相册', 'ctl' => 'shop/album:create', 'nav' => 'shop/album:index'),
                    array('title' => '修改相册', 'ctl' => 'shop/album:edit', 'nav' => 'shop/album:index'),
                    array('title' => '删除相册', 'ctl' => 'shop/album:delete', 'nav' => 'shop/album:index'),
                    array('title' => '管理相册', 'ctl' => 'shop/album:detail', 'nav' => 'shop/album:index'),
                    array('title' => '修改设置', 'ctl' => 'shop/print:edit', 'nav' => 'shop/print:index'),
                    array('title' => '删除设置', 'ctl' => 'shop/print:delete', 'nav' => 'shop/print:index'),
                    array('title' => '开启或静默', 'ctl' => 'shop/print:change', 'nav' => 'shop/print:index'),
                    array('title' => '店铺评价', 'ctl' => 'shop/comment:index', 'menu' => true),
                    array('title' => '店铺评价回复', 'ctl' => 'shop/comment:reply', 'nav' => 'shop/comment:index'),
                    array('title' => '店铺评价详情', 'ctl' => 'shop/comment:detail', 'nav' => 'shop/comment:index'),
                    array('title' => '外卖评价', 'ctl' => 'waimai/comment:index', 'menu' => true),
                    array('title' => '外卖评价', 'ctl' => 'waimai/comment:items', 'nav' => 'waimai/comment:index'),
                    array('title' => '外卖评价回复', 'ctl' => 'waimai/comment:reply', 'nav' => 'waimai/comment:index'),
                    array('title' => '外卖评价详情', 'ctl' => 'waimai/comment:detail', 'nav' => 'waimai/comment:index'),
                    array('title' => '店铺评价回复dialog', 'ctl' => 'shop/comment:reply_dialog', 'nav' => 'shop/comment:index'),
                    array('title' => '外卖评价回复dialog', 'ctl' => 'waimai/comment:reply_dialog', 'nav' => 'waimai/comment:index'),
                    array('title' => '我的客户', 'ctl' => 'shop/member:index', 'menu' => true),
                    array('title' => '我的粉丝', 'ctl' => 'shop/member:fans', 'menu' => true),
                    array('title' => '详情', 'ctl' => 'shop/member:detail', 'nav' => 'shop/member:index'),
                    array('title' => '资金管理', 'ctl' => 'shop/money:index', 'menu' => true),
                    array('title' => '提现日志', 'ctl' => 'shop/money:txlog', 'menu' => true),
                    array('title' => '提现', 'ctl' => 'shop/money:tixian', 'nav' => 'shop/money:txlog'),
                )
            )
        )
    );



