<?php
/**
 * Copy Right IJH.CC
 * Each engineer has a duty to keep the code elegant
 * $Id$
 */
if(!defined('__CORE_DIR')){
    exit("Access Denied");
}
return array (
    'shop_id' =>
        array (
            'field' => 'shop_id',
            'label' => '商户ID',
            'pk' => true,
            'add' => true,
            'edit' => false,
            'html' => false,
            'empty' => false,
            'show' => false,
            'list' => false,
            'type' => 'text',
            'comment' => '',
            'default' => '',
            'SO' => '=',
        ),
    'app_auth_token' =>
        array (
            'field' => 'app_auth_token',
            'label' => '商户授权令牌',
            'pk' => false,
            'add' => true,
            'edit' => true,
            'html' => false,
            'empty' => true,
            'show' => false,
            'list' => false,
            'type' => 'text',
            'comment' => '',
            'default' => '',
            'SO' => false,
        ),
    'app_refresh_token' =>
        array (
            'field' => 'app_refresh_token',
            'label' => '刷新令牌时使用',
            'pk' => false,
            'add' => true,
            'edit' => true,
            'html' => false,
            'empty' => true,
            'show' => false,
            'list' => false,
            'type' => 'text',
            'comment' => '',
            'default' => '',
            'SO' => false,
        ),
    'auth_app_id' =>
        array (
            'field' => 'auth_app_id',
            'label' => '授权商户的AppId',
            'pk' => false,
            'add' => true,
            'edit' => true,
            'html' => false,
            'empty' => true,
            'show' => false,
            'list' => false,
            'type' => 'text',
            'comment' => '',
            'default' => '',
            'SO' => false,
        ),
    'user_id' =>
        array (
            'field' => 'user_id',
            'label' => '授权商户的ID',
            'pk' => false,
            'add' => true,
            'edit' => true,
            'html' => false,
            'empty' => true,
            'show' => false,
            'list' => false,
            'type' => 'text',
            'comment' => '',
            'default' => '',
            'SO' => false,
        ),
    'expires_in' =>
        array (
            'field' => 'expires_in',
            'label' => '令牌有效期',
            'pk' => false,
            'add' => true,
            'edit' => true,
            'html' => false,
            'empty' => true,
            'show' => false,
            'list' => false,
            'type' => 'int',
            'comment' => '',
            'default' => '',
            'SO' => false,
        ),
    're_expires_in' =>
        array (
            'field' => 're_expires_in',
            'label' => '刷新令牌有效期',
            'pk' => false,
            'add' => true,
            'edit' => true,
            'html' => false,
            'empty' => true,
            'show' => false,
            'list' => false,
            'type' => 'text',
            'comment' => '',
            'default' => '',
            'SO' => false,
        ),
    'expire_time' =>
        array (
            'field' => 'expire_time',
            'label' => '过期时间',
            'pk' => false,
            'add' => true,
            'edit' => true,
            'html' => false,
            'empty' => true,
            'show' => false,
            'list' => true,
            'type' => 'unixtime',
            'comment' => '',
            'default' => '',
            'SO' => 'betweendate',
        ),
    'status' =>
        array (
            'field' => 'status',
            'label' => '审核状态',
            'pk' => false,
            'add' => true,
            'edit' => true,
            'html' => false,
            'empty' => true,
            'show' => false,
            'list' => true,
            'type' => 'int',
            'comment' => '',
            'default' => '',
            'SO' => false,
        ),
);