<?php
/**
 * Copy Right IJH.CC
 * Each engineer has a duty to keep the code elegant
 * $Id$
 */
if(!defined('__CORE_DIR')){
    exit("Access Denied");
}
return array (
  'shop_id' => 
  array (
    'field' => 'shop_id',
    'label' => '商户',
    'pk' => true,
    'add' => true,
    'edit' => false,
    'html' => false,
    'empty' => false,
    'show' => true,
    'list' => true,
    'type' => 'int',
    'comment' => '',
    'default' => '',
    'SO' => false,
  ),
  'id_name' => 
  array (
    'field' => 'id_name',
    'label' => '真实姓名',
    'pk' => false,
    'add' => true,
    'edit' => true,
    'html' => false,
    'empty' => false,
    'show' => true,
    'list' => true,
    'type' => 'text',
    'comment' => '',
    'default' => '',
    'SO' => false,
  ),
  'id_number' => 
  array (
    'field' => 'id_number',
    'label' => '身份证号',
    'pk' => false,
    'add' => true,
    'edit' => true,
    'html' => false,
    'empty' => false,
    'show' => true,
    'list' => true,
    'type' => 'text',
    'comment' => '',
    'default' => '',
    'SO' => false,
  ),
  'id_photo1' => 
  array (
    'field' => 'id_photo1',
    'label' => '身份证正面',
    'pk' => false,
    'add' => true,
    'edit' => true,
    'html' => false,
    'empty' => false,
    'show' => true,
    'list' => true,
    'type' => 'photo',
    'comment' => '',
    'default' => '',
    'SO' => false,
  ),
  'id_photo2' => 
  array (
    'field' => 'id_photo2',
    'label' => '身份证反面',
    'pk' => false,
    'add' => true,
    'edit' => true,
    'html' => false,
    'empty' => false,
    'show' => true,
    'list' => true,
    'type' => 'photo',
    'comment' => '',
    'default' => '',
    'SO' => false,
  ),
  'id_photo3' => 
  array (
    'field' => 'id_photo3',
    'label' => '手持身份证',
    'pk' => false,
    'add' => true,
    'edit' => true,
    'html' => false,
    'empty' => false,
    'show' => true,
    'list' => true,
    'type' => 'photo',
    'comment' => '',
    'default' => '',
    'SO' => false,
  ),
  'mentou_photo' => 
  array (
    'field' => 'mentou_photo',
    'label' => '店铺门头',
    'pk' => false,
    'add' => true,
    'edit' => true,
    'html' => false,
    'empty' => true,
    'show' => true,
    'list' => true,
    'type' => 'photo',
    'comment' => '',
    'default' => '',
    'SO' => false,
  ),
  'shop_photo1' => 
  array (
    'field' => 'shop_photo1',
    'label' => '内景图',
    'pk' => false,
    'add' => true,
    'edit' => true,
    'html' => false,
    'empty' => true,
    'show' => true,
    'list' => true,
    'type' => 'photo',
    'comment' => '',
    'default' => '',
    'SO' => false,
  ),
  'shop_photo2' => 
  array (
    'field' => 'shop_photo2',
    'label' => '内景图',
    'pk' => false,
    'add' => true,
    'edit' => true,
    'html' => false,
    'empty' => true,
    'show' => true,
    'list' => true,
    'type' => 'photo',
    'comment' => '',
    'default' => '',
    'SO' => false,
  ),
  'shop_photo3' => 
  array (
    'field' => 'shop_photo3',
    'label' => '内景图',
    'pk' => false,
    'add' => true,
    'edit' => true,
    'html' => false,
    'empty' => true,
    'show' => true,
    'list' => true,
    'type' => 'photo',
    'comment' => '',
    'default' => '',
    'SO' => false,
  ),
  'verify' => 
  array (
    'field' => 'verify',
    'label' => '状态',
    'pk' => false,
    'add' => true,
    'edit' => true,
    'html' => false,
    'empty' => true,
    'show' => true,
    'list' => true,
    'type' => 'int',
    'comment' => '',
    'default' => '',
    'SO' => false,
  ),
  'updatetime' =>
    array (
        'field' => 'updatetime',
        'label' => '更新时间',
        'pk' => false,
        'add' => true,
        'edit' => true,
        'html' => false,
        'empty' => false,
        'show' => false,
        'list' => true,
        'type' => 'updatetime',
        'comment' => '',
        'default' => '',
        'SO' => 'betweendate',
    ),
    'refuse' => 
      array (
        'field' => 'refuse',
        'label' => '拒绝原因',
        'pk' => false,
        'add' => false,
        'edit' => true,
        'html' => false,
        'empty' => true,
        'show' => true,
        'list' => true,
        'type' => 'text',
        'comment' => '',
        'default' => '',
        'SO' => false,
      ),

);