<?php
/**
 * Copy Right IJH.CC
 * Each engineer has a duty to keep the code elegant
 * $Id$
 */
if(!defined('__CORE_DIR')){
    exit("Access Denied");
}
return array (
  'account_id' => 
  array (
    'field' => 'account_id',
    'label' => 'account_id',
    'pk' => true,
    'add' => true,
    'edit' => false,
    'html' => false,
    'empty' => true,
    'show' => false,
    'list' => true,
    'type' => 'text',
    'comment' => '',
    'default' => '',
    'SO' => false,
  ),
  'shop_id' => 
  array (
    'field' => 'shop_id',
    'label' => '店铺id',
    'pk' => false,
    'add' => true,
    'edit' => true,
    'html' => false,
    'empty' => true,
    'show' => false,
    'list' => true,
    'type' => 'shop',
    'comment' => '',
    'default' => '',
    'SO' => false,
  ),
  'platform' => 
  array (
    'field' => 'platform',
    'label' => '平台',
    'pk' => false,
    'add' => true,
    'edit' => true,
    'html' => false,
    'empty' => true,
    'show' => false,
    'list' => true,
    'type' => 'select',
    'comment' => '',
    'default' => '',
    'SO' => '=',
  ),
  'user_name' => 
  array (
    'field' => 'user_name',
    'label' => '登录用户名',
    'pk' => false,
    'add' => true,
    'edit' => true,
    'html' => false,
    'empty' => true,
    'show' => false,
    'list' => true,
    'type' => 'text',
    'comment' => '',
    'default' => '',
    'SO' => 'like',
  ),
  'password' => 
  array (
    'field' => 'password',
    'label' => '登录密码',
    'pk' => false,
    'add' => true,
    'edit' => true,
    'html' => false,
    'empty' => true,
    'show' => false,
    'list' => true,
    'type' => 'text',
    'comment' => '',
    'default' => '',
    'SO' => false,
  ),
  'login_type' => 
  array (
    'field' => 'login_type',
    'label' => '登录方式',
    'pk' => false,
    'add' => true,
    'edit' => true,
    'html' => false,
    'empty' => true,
    'show' => false,
    'list' => true,
    'type' => 'select',
    'comment' => '登陆方式, 比如 cookie登陆, 和  token登陆,  不同的方法, 返回数据区分,',
    'default' => 'cookie',
    'SO' => false,
  ),
  'login_info' => 
  array (
    'field' => 'login_info',
    'label' => '登录信息',
    'pk' => false,
    'add' => true,
    'edit' => true,
    'html' => false,
    'empty' => true,
    'show' => false,
    'list' => true,
    'type' => 'text',
    'comment' => '存储登陆返回有效值,',
    'default' => '',
    'SO' => false,
  ),
  'login_time' => 
  array (
    'field' => 'login_time',
    'label' => 'login_time',
    'pk' => false,
    'add' => true,
    'edit' => true,
    'html' => false,
    'empty' => true,
    'show' => false,
    'list' => true,
    'type' => 'text',
    'comment' => '最后一次登陆时间,  10s 内,不要重复请求接口, 防止多次登录',
    'default' => '',
    'SO' => false,
  ),
  'dateline' => 
  array (
    'field' => 'dateline',
    'label' => 'dateline',
    'pk' => false,
    'add' => true,
    'edit' => false,
    'html' => false,
    'empty' => true,
    'show' => false,
    'list' => true,
    'type' => 'text',
    'comment' => '',
    'default' => '',
    'SO' => false,
  ),
);