<?php
/**
 * Copy Right IJH.CC
 * Each engineer has a duty to keep the code elegant
 * $Id$
 */

if(!defined('__CORE_DIR')){
    exit("Access Denied");
}

return array (
  'id' => 
  array (
    'field' => 'id',
    'label' => 'ID',
    'pk' => true,
    'add' => true,
    'edit' => true,
    'html' => false,
    'empty' => false,
    'show' => true,
    'list' => true,
    'type' => 'int',
    'comment' => 'ID',
    'default' => '',
    'SO' => false,
  ),
  'order_id' => 
  array (
    'field' => 'order_id',
    'label' => 'ID',
    'pk' => false,
    'add' => true,
    'edit' => true,
    'html' => false,
    'empty' => false,
    'show' => true,
    'list' => true,
    'type' => 'int',
    'comment' => '订单ID',
    'default' => '',
    'SO' => false,
  ),
  'order_status' => 
  array (
    'field' => 'order_status',
    'label' => 'ID',
    'pk' => false,
    'add' => true,
    'edit' => true,
    'html' => false,
    'empty' => false,
    'show' => true,
    'list' => true,
    'type' => 'int',
    'comment' => '订单状态',
    'default' => '',
    'SO' => false,
  ),
  'type' => 
  array (
    'field' => 'type',
    'label' => '类型',
    'pk' => false,
    'add' => true,
    'edit' => true,
    'html' => false,
    'empty' => true,
    'show' => true,
    'list' => true,
    'type' => 'text',
    'comment' => '类型',
    'default' => '0',
    'SO' => false,
  ),
  'o_addr' => 
  array (
    'field' => 'o_addr',
    'label' => '取件/购买地址',
    'pk' => false,
    'add' => true,
    'edit' => true,
    'html' => false,
    'empty' => true,
    'show' => true,
    'list' => true,
    'type' => 'text',
    'comment' => '取件/购买地址',
    'default' => '',
    'SO' => false,
  ),
  'o_house' => 
  array (
    'field' => 'o_house',
    'label' => '取件/购买门号',
    'pk' => false,
    'add' => true,
    'edit' => true,
    'html' => false,
    'empty' => true,
    'show' => true,
    'list' => true,
    'type' => 'text',
    'comment' => '取件/购买门号',
    'default' => '',
    'SO' => false,
  ),
  'o_contact' => 
  array (
    'field' => 'o_contact',
    'label' => '取件/购买联系人',
    'pk' => false,
    'add' => true,
    'edit' => true,
    'html' => false,
    'empty' => true,
    'show' => true,
    'list' => true,
    'type' => 'text',
    'comment' => '取件/购买联系人',
    'default' => '',
    'SO' => false,
  ),
  'o_mobile' => 
  array (
    'field' => 'o_mobile',
    'label' => '取件/购买电话',
    'pk' => false,
    'add' => true,
    'edit' => true,
    'html' => false,
    'empty' => true,
    'show' => true,
    'list' => true,
    'type' => 'text',
    'comment' => '取件/购买电话',
    'default' => '',
    'SO' => false,
  ),
  'o_time' => 
  array (
    'field' => 'o_time',
    'label' => '取件时间',
    'pk' => false,
    'add' => true,
    'edit' => true,
    'html' => false,
    'empty' => true,
    'show' => true,
    'list' => true,
    'type' => 'unixtime',
    'comment' => '收件时间',
    'default' => '',
    'SO' => false,
  ),
  'time' => 
  array (
    'field' => 'time',
    'label' => '收件时间',
    'pk' => false,
    'add' => true,
    'edit' => true,
    'html' => false,
    'empty' => true,
    'show' => true,
    'list' => true,
    'type' => 'unixtime',
    'comment' => '取件时间',
    'default' => '',
    'SO' => false,
  ),
  'paotui_amount' => 
  array (
    'field' => 'paotui_amount',
    'label' => '跑腿费用',
    'pk' => false,
    'add' => true,
    'edit' => true,
    'html' => false,
    'empty' => false,
    'show' => true,
    'list' => true,
    'type' => 'number',
    'comment' => '跑腿费用',
    'default' => '0.00',
    'SO' => false,
  ),
  'danbao_amount' => 
  array (
    'field' => 'danbao_amount',
    'label' => '担保托管金额',
    'pk' => false,
    'add' => true,
    'edit' => true,
    'html' => false,
    'empty' => true,
    'show' => true,
    'list' => true,
    'type' => 'number',
    'comment' => '担保托管金额',
    'default' => '0.00',
    'SO' => false,
  ),
  'jiesuan_amount' => 
  array (
    'field' => 'jiesuan_amount',
    'label' => '结算金额',
    'pk' => false,
    'add' => true,
    'edit' => true,
    'html' => false,
    'empty' => true,
    'show' => true,
    'list' => true,
    'type' => 'number',
    'comment' => '结算金额',
    'default' => '0.00',
    'SO' => false,
  ),
);