<?php
/**
 * Copy Right IJH.CC
 * Each engineer has a duty to keep the code elegant
 * $Id$
 */

if(!defined('__CORE_DIR')){
    exit("Access Denied");
}

return array (
  'detail_id' => 
  array (
    'field' => 'detail_id',
    'label' => 'detail_id',
    'pk' => true,
    'add' => false,
    'edit' => true,
    'html' => false,
    'empty' => true,
    'show' => true,
    'list' => true,
    'type' => 'text',
    'comment' => '',
    'default' => '',
    'SO' => false,
  ),
  'po_id' => 
  array (
    'field' => 'po_id',
    'label' => '收银id',
    'pk' => false,
    'add' => true,
    'edit' => true,
    'html' => false,
    'empty' => true,
    'show' => true,
    'list' => true,
    'type' => 'text',
    'comment' => '收银id',
    'default' => '',
    'SO' => false,
  ),
  'code' => 
  array (
    'field' => 'code',
    'label' => 'code',
    'pk' => false,
    'add' => true,
    'edit' => true,
    'html' => false,
    'empty' => true,
    'show' => true,
    'list' => true,
    'type' => 'text',
    'comment' => '支付宝:返回code',
    'default' => '',
    'SO' => false,
  ),
  'msg' => 
  array (
    'field' => 'msg',
    'label' => 'msg',
    'pk' => false,
    'add' => true,
    'edit' => true,
    'html' => false,
    'empty' => true,
    'show' => true,
    'list' => true,
    'type' => 'text',
    'comment' => '支付宝:msg',
    'default' => '',
    'SO' => false,
  ),
  'buyer_logon_id' => 
  array (
    'field' => 'buyer_logon_id',
    'label' => 'buyer_logon_id',
    'pk' => false,
    'add' => true,
    'edit' => true,
    'html' => false,
    'empty' => true,
    'show' => true,
    'list' => true,
    'type' => 'text',
    'comment' => '',
    'default' => '',
    'SO' => false,
  ),
  'buyer_pay_amount' => 
  array (
    'field' => 'buyer_pay_amount',
    'label' => 'buyer_pay_amount',
    'pk' => false,
    'add' => true,
    'edit' => true,
    'html' => false,
    'empty' => true,
    'show' => true,
    'list' => true,
    'type' => 'text',
    'comment' => '',
    'default' => '',
    'SO' => false,
  ),
  'buyer_user_id' => 
  array (
    'field' => 'buyer_user_id',
    'label' => 'buyer_user_id',
    'pk' => false,
    'add' => true,
    'edit' => true,
    'html' => false,
    'empty' => true,
    'show' => true,
    'list' => true,
    'type' => 'text',
    'comment' => '',
    'default' => '',
    'SO' => false,
  ),
  'fund_bill_list' => 
  array (
    'field' => 'fund_bill_list',
    'label' => 'fund_bill_list',
    'pk' => false,
    'add' => true,
    'edit' => true,
    'html' => false,
    'empty' => true,
    'show' => true,
    'list' => true,
    'type' => 'text',
    'comment' => 'json格式化数据',
    'default' => '',
    'SO' => false,
  ),
  'gmt_payment' => 
  array (
    'field' => 'gmt_payment',
    'label' => '支付时间',
    'pk' => false,
    'add' => true,
    'edit' => true,
    'html' => false,
    'empty' => true,
    'show' => true,
    'list' => true,
    'type' => 'text',
    'comment' => '支付时间',
    'default' => '',
    'SO' => false,
  ),
  'invoice_amount' => 
  array (
    'field' => 'invoice_amount',
    'label' => 'invoice_amount',
    'pk' => false,
    'add' => true,
    'edit' => true,
    'html' => false,
    'empty' => true,
    'show' => true,
    'list' => true,
    'type' => 'text',
    'comment' => '',
    'default' => '',
    'SO' => false,
  ),
  'open_id' => 
  array (
    'field' => 'open_id',
    'label' => 'open_id',
    'pk' => false,
    'add' => true,
    'edit' => true,
    'html' => false,
    'empty' => true,
    'show' => true,
    'list' => true,
    'type' => 'text',
    'comment' => '',
    'default' => '',
    'SO' => false,
  ),
  'out_trade_no' => 
  array (
    'field' => 'out_trade_no',
    'label' => 'out_trade_no',
    'pk' => false,
    'add' => true,
    'edit' => true,
    'html' => false,
    'empty' => true,
    'show' => true,
    'list' => true,
    'type' => 'text',
    'comment' => '',
    'default' => '',
    'SO' => false,
  ),
  'point_amount' => 
  array (
    'field' => 'point_amount',
    'label' => 'point_amount',
    'pk' => false,
    'add' => true,
    'edit' => true,
    'html' => false,
    'empty' => true,
    'show' => true,
    'list' => true,
    'type' => 'text',
    'comment' => '',
    'default' => '0.00',
    'SO' => false,
  ),
  'receipt_amount' => 
  array (
    'field' => 'receipt_amount',
    'label' => 'receipt_amount',
    'pk' => false,
    'add' => true,
    'edit' => true,
    'html' => false,
    'empty' => true,
    'show' => true,
    'list' => true,
    'type' => 'text',
    'comment' => '',
    'default' => '0.00',
    'SO' => false,
  ),
  'total_amount' => 
  array (
    'field' => 'total_amount',
    'label' => '总金额',
    'pk' => false,
    'add' => true,
    'edit' => true,
    'html' => false,
    'empty' => true,
    'show' => true,
    'list' => true,
    'type' => 'text',
    'comment' => '总金额',
    'default' => '0.00',
    'SO' => false,
  ),
  'trade_no' => 
  array (
    'field' => 'trade_no',
    'label' => '第三方交易id',
    'pk' => false,
    'add' => true,
    'edit' => true,
    'html' => false,
    'empty' => true,
    'show' => true,
    'list' => true,
    'type' => 'text',
    'comment' => '第三方交易id,类似危险transaction_id',
    'default' => '',
    'SO' => false,
  ),
  'is_pay' => 
  array (
    'field' => 'is_pay',
    'label' => '支付状态',
    'pk' => false,
    'add' => true,
    'edit' => true,
    'html' => false,
    'empty' => true,
    'show' => true,
    'list' => true,
    'type' => 'text',
    'comment' => '0:未支付,1:支付成功',
    'default' => '',
    'SO' => false,
  ),
  'is_back' => 
  array (
    'field' => 'is_back',
    'label' => '退款状态',
    'pk' => false,
    'add' => true,
    'edit' => true,
    'html' => false,
    'empty' => true,
    'show' => true,
    'list' => true,
    'type' => 'text',
    'comment' => '0:无退款,1:已退款',
    'default' => '',
    'SO' => false,
  ),
  'back_time' => 
  array (
    'field' => 'back_time',
    'label' => '退款时间',
    'pk' => false,
    'add' => true,
    'edit' => true,
    'html' => false,
    'empty' => true,
    'show' => true,
    'list' => true,
    'type' => 'text',
    'comment' => '退款时间',
    'default' => '',
    'SO' => false,
  ),
  'back_info' => 
  array (
    'field' => 'back_info',
    'label' => '退款详情',
    'pk' => false,
    'add' => true,
    'edit' => true,
    'html' => false,
    'empty' => true,
    'show' => true,
    'list' => true,
    'type' => 'text',
    'comment' => '退款信息详情',
    'default' => '',
    'SO' => false,
  ),
  'dateline' => 
  array (
    'field' => 'dateline',
    'label' => 'dateline',
    'pk' => false,
    'add' => true,
    'edit' => true,
    'html' => false,
    'empty' => true,
    'show' => true,
    'list' => true,
    'type' => 'text',
    'comment' => '',
    'default' => '',
    'SO' => false,
  ),
);