<?php
/**
 * Copy Right IJH.CC
 * Each engineer has a duty to keep the code elegant
 * $Id$
 */

if(!defined('__CORE_DIR')){
    exit("Access Denied");
}

return array (
  'order_id' => 
  array (
    'field' => 'order_id',
    'label' => '订单ID',
    'pk' => true,
    'add' => true,
    'edit' => true,
    'html' => false,
    'empty' => true,
    'show' => true,
    'list' => true,
    'type' => 'int',
    'comment' => '订单ID',
    'default' => '',
    'SO' => '=',
  ),
  'city_id' => 
  array (
    'field' => 'city_id',
    'label' => '城市ID',
    'pk' => false,
    'add' => true,
    'edit' => true,
    'html' => false,
    'empty' => true,
    'show' => true,
    'list' => true,
    'type' => 'int',
    'comment' => '城市ID',
    'default' => '',
    'SO' => '=',
  ),
  'shop_id' => 
  array (
    'field' => 'shop_id',
    'label' => '商户ID',
    'pk' => false,
    'add' => true,
    'edit' => true,
    'html' => false,
    'empty' => true,
    'show' => true,
    'list' => true,
    'type' => 'int',
    'comment' => '商户ID',
    'default' => '',
    'SO' => '=',
  ),
  'staff_id' => 
  array (
    'field' => 'staff_id',
    'label' => '服务人员ID',
    'pk' => false,
    'add' => true,
    'edit' => true,
    'html' => false,
    'empty' => true,
    'show' => true,
    'list' => true,
    'type' => 'int',
    'comment' => '服务人员ID',
    'default' => '',
    'SO' => '=',
  ),
  'uid' => 
  array (
    'field' => 'uid',
    'label' => '用户UID',
    'pk' => false,
    'add' => true,
    'edit' => true,
    'html' => false,
    'empty' => false,
    'show' => true,
    'list' => true,
    'type' => 'int',
    'comment' => '用户UID',
    'default' => '',
    'SO' => '=',
  ),
  'from' => 
  array (
    'field' => 'from',
    'label' => '订单类型',
    'pk' => false,
    'add' => true,
    'edit' => true,
    'html' => false,
    'empty' => false,
    'show' => true,
    'list' => true,
    'type' => 'text',
    'comment' => '订单类型： tuan:团购,waimai:外卖,paotui:跑腿,weixiu:维修,maidan:买单,house:家政',
    'default' => '',
    'SO' => '=',
  ),
  'order_status' => 
  array (
    'field' => 'order_status',
    'label' => '订单状态',
    'pk' => false,
    'add' => true,
    'edit' => true,
    'html' => false,
    'empty' => true,
    'show' => true,
    'list' => true,
    'type' => 'int',
    'comment' => '订单状态',
    'default' => '',
    'SO' => '=',
  ),
  'online_pay' => 
  array (
    'field' => 'online_pay',
    'label' => '付款方式',
    'pk' => false,
    'add' => true,
    'edit' => true,
    'html' => false,
    'empty' => true,
    'show' => true,
    'list' => true,
    'type' => 'int',
    'comment' => '付款方式   0:货到付款,1:在线支付',
    'default' => '',
    'SO' => false,
  ),
  'pay_status' => 
  array (
    'field' => 'pay_status',
    'label' => '支付状态',
    'pk' => false,
    'add' => true,
    'edit' => true,
    'html' => false,
    'empty' => true,
    'show' => true,
    'list' => true,
    'type' => 'int',
    'comment' => '支付状态 0:未支付，1:已支付',
    'default' => '',
    'SO' => '=',
  ),
  'trade_no' => 
  array (
    'field' => 'trade_no',
    'label' => '支付状态',
    'pk' => false,
    'add' => true,
    'edit' => true,
    'html' => false,
    'empty' => true,
    'show' => true,
    'list' => true,
    'type' => 'int',
    'comment' => '支付流水号',
    'default' => '',
    'SO' => false,
  ),
  'total_price' => 
  array (
    'field' => 'total_price',
    'label' => '订单总金额',
    'pk' => false,
    'add' => true,
    'edit' => true,
    'html' => false,
    'empty' => true,
    'show' => true,
    'list' => true,
    'type' => 'number',
    'comment' => '订单总金额',
    'default' => '',
    'SO' => false,
  ),
  'hongbao_id' => 
  array (
    'field' => 'hongbao_id',
    'label' => '红包ID',
    'pk' => false,
    'add' => true,
    'edit' => true,
    'html' => false,
    'empty' => true,
    'show' => true,
    'list' => true,
    'type' => 'int',
    'comment' => '红包ID',
    'default' => '',
    'SO' => false,
  ),
  'hongbao' => 
  array (
    'field' => 'hongbao',
    'label' => '红包金额',
    'pk' => false,
    'add' => true,
    'edit' => true,
    'html' => false,
    'empty' => true,
    'show' => true,
    'list' => true,
    'type' => 'number',
    'comment' => '红包金额',
    'default' => '0.00',
    'SO' => false,
  ),
  'youhui_amount' => 
  array (
    'field' => 'youhui_amount',
    'label' => '优惠总金额',
    'pk' => false,
    'add' => true,
    'edit' => true,
    'html' => false,
    'empty' => true,
    'show' => true,
    'list' => true,
    'type' => 'number',
    'comment' => '优惠总金额',
    'default' => '0.00',
    'SO' => false,
  ),
  'money' => 
  array (
    'field' => 'money',
    'label' => '优惠总金额',
    'pk' => false,
    'add' => true,
    'edit' => true,
    'html' => false,
    'empty' => true,
    'show' => true,
    'list' => true,
    'type' => 'number',
    'comment' => '余额抵扣',
    'default' => '',
    'SO' => false,
  ),
  'amount' => 
  array (
    'field' => 'amount',
    'label' => '需支付金额',
    'pk' => false,
    'add' => true,
    'edit' => true,
    'html' => false,
    'empty' => true,
    'show' => true,
    'list' => true,
    'type' => 'number',
    'comment' => '需支付金额 =product_price+freight-order_youhui-first_youhui-hongbao-money',
    'default' => '',
    'SO' => false,
  ),
  'o_lng' => 
  array (
    'field' => 'o_lng',
    'label' => '需支付金额',
    'pk' => false,
    'add' => true,
    'edit' => true,
    'html' => false,
    'empty' => true,
    'show' => true,
    'list' => true,
    'type' => 'number',
    'comment' => '接单起点经度坐标',
    'default' => '',
    'SO' => false,
  ),
  'o_lat' => 
  array (
    'field' => 'o_lat',
    'label' => '接单起点纬度坐标',
    'pk' => false,
    'add' => true,
    'edit' => true,
    'html' => false,
    'empty' => true,
    'show' => true,
    'list' => true,
    'type' => 'number',
    'comment' => '接单起点纬度坐标',
    'default' => '',
    'SO' => false,
  ),
  'contact' => 
  array (
    'field' => 'contact',
    'label' => '联系人',
    'pk' => false,
    'add' => true,
    'edit' => true,
    'html' => false,
    'empty' => true,
    'show' => true,
    'list' => true,
    'type' => 'text',
    'comment' => '联系人',
    'default' => '',
    'SO' => false,
  ),
  'mobile' => 
  array (
    'field' => 'mobile',
    'label' => '手机号',
    'pk' => false,
    'add' => true,
    'edit' => true,
    'html' => false,
    'empty' => true,
    'show' => true,
    'list' => true,
    'type' => 'mobile',
    'comment' => '手机号',
    'default' => '',
    'SO' => false,
  ),
  'addr' => 
  array (
    'field' => 'addr',
    'label' => '收货地址',
    'pk' => false,
    'add' => true,
    'edit' => true,
    'html' => false,
    'empty' => true,
    'show' => true,
    'list' => true,
    'type' => 'text',
    'comment' => '收货地址',
    'default' => '',
    'SO' => false,
  ),
  'house' => 
  array (
    'field' => 'house',
    'label' => '收货地小区门牌号',
    'pk' => false,
    'add' => true,
    'edit' => true,
    'html' => false,
    'empty' => true,
    'show' => true,
    'list' => true,
    'type' => 'text',
    'comment' => '收货地小区门牌号',
    'default' => '',
    'SO' => false,
  ),
  'lng' => 
  array (
    'field' => 'lng',
    'label' => '收货地纬度坐标',
    'pk' => false,
    'add' => true,
    'edit' => true,
    'html' => false,
    'empty' => true,
    'show' => true,
    'list' => true,
    'type' => 'number',
    'comment' => '收货地纬度坐标',
    'default' => '',
    'SO' => false,
  ),
  'lat' => 
  array (
    'field' => 'lat',
    'label' => '收货地经度坐标',
    'pk' => false,
    'add' => true,
    'edit' => true,
    'html' => false,
    'empty' => true,
    'show' => true,
    'list' => true,
    'type' => 'number',
    'comment' => '收货地经度坐标',
    'default' => '',
    'SO' => false,
  ),
  'day' => 
  array (
    'field' => 'day',
    'label' => '订单日期',
    'pk' => false,
    'add' => true,
    'edit' => true,
    'html' => false,
    'empty' => true,
    'show' => true,
    'list' => true,
    'type' => 'int',
    'comment' => '订单日期格式20160220',
    'default' => '',
    'SO' => '=',
  ),
  'comment_status' => 
  array (
    'field' => 'comment_status',
    'label' => '订单评价',
    'pk' => false,
    'add' => true,
    'edit' => true,
    'html' => false,
    'empty' => true,
    'show' => true,
    'list' => true,
    'type' => 'int',
    'comment' => '订单是否已评价  0：未评价  1：已评价',
    'default' => '',
    'SO' => '=',
  ),
  'clientip' => 
  array (
    'field' => 'clientip',
    'label' => '客户IP',
    'pk' => false,
    'add' => true,
    'edit' => true,
    'html' => false,
    'empty' => false,
    'show' => true,
    'list' => true,
    'type' => 'clientip',
    'comment' => '客户IP',
    'default' => '',
    'SO' => false,
  ),
  
  'dateline' => 
  array (
    'field' => 'dateline',
    'label' => '创建时间',
    'pk' => false,
    'add' => true,
    'edit' => true,
    'html' => false,
    'empty' => false,
    'show' => true,
    'list' => true,
    'type' => 'dateline',
    'comment' => '创建时间',
    'default' => '',
    'SO' => 'betweendate',
  ),
   'pei_time' => 
  array (
    'field' => 'pei_time',
    'label' => '配送速度',
    'pk' => false,
    'add' => true,
    'edit' => true,
    'html' => false,
    'empty' => true,
    'show' => true,
    'list' => true,
    'type' => 'int',
    'comment' => '配送速度',
    'default' => '',
    'SO' => 'betweendate',
  ),
   'jd_time' => 
  array (
    'field' => 'jd_time',
    'label' => '接单时间',
    'pk' => false,
    'add' => true,
    'edit' => true,
    'html' => false,
    'empty' => false,
    'show' => true,
    'list' => true,
    'type' => 'dateline',
    'comment' => '接单时间',
    'default' => '',
    'SO' => 'betweendate',
  ),
  'cui_time' => 
  array (
    'field' => 'cui_time',
    'label' => '用户催单时间',
    'pk' => false,
    'add' => true,
    'edit' => true,
    'html' => false,
    'empty' => false,
    'show' => true,
    'list' => true,
    'type' => 'dateline',
    'comment' => '用户催单时间',
    'default' => '',
    'SO' => 'betweendate',
  ),
   'pay_time' => 
  array (
    'field' => 'pay_time',
    'label' => '付款时间',
    'pk' => false,
    'add' => true,
    'edit' => true,
    'html' => false,
    'empty' => false,
    'show' => true,
    'list' => true,
    'type' => 'dateline',
    'comment' => '付款时间',
    'default' => '',
    'SO' => 'betweendate',
  ),
  'pay_code' => 
  array (
    'field' => 'pay_code',
    'label' => '支付类型',
    'pk' => false,
    'add' => true,
    'edit' => true,
    'html' => false,
    'empty' => true,
    'show' => true,
    'list' => true,
    'type' => 'text',
    'comment' => '支付类型   wxpay:微信, alipay:支付宝, money:余额',
    'default' => '',
    'SO' => false,
  ),
    'closed' => 
  array (
    'field' => 'closed',
    'label' => '是否删除',
    'pk' => false,
    'add' => true,
    'edit' => true,
    'html' => false,
    'empty' => true,
    'show' => true,
    'list' => true,
    'type' => 'int',
    'comment' => '是否删除',
    'default' => '',
    'SO' => false,
  ),
    'lasttime' => 
  array (
    'field' => 'lasttime',
    'label' => '最后更新时间',
    'pk' => false,
    'add' => true,
    'edit' => true,
    'html' => false,
    'empty' => true,
    'show' => true,
    'list' => true,
    'type' => 'dateline',
    'comment' => '最后更新时间',
    'default' => '',
    'SO' => 'betweendate',
  ),
);