<?php
/**
 * Copy Right IJH.CC
 * Each engineer has a duty to keep the code elegant
 * $Id$
 */
if(!defined('__CORE_DIR')){
    exit("Access Denied");
}
return array (
  'item_id' => 
  array (
    'field' => 'item_id',
    'label' => '运费模板ID',
    'pk' => true,
    'add' => true,
    'edit' => false,
    'html' => true,
    'empty' => false,
    'show' => true,
    'list' => true,
    'type' => 'int',
    'comment' => '运费模板ID',
    'default' => '',
    'SO' => false,
  ),
  'tpl_id' => 
  array (
    'field' => 'tpl_id',
    'label' => '运费模板ID',
    'pk' => false,
    'add' => true,
    'edit' => true,
    'html' => true,
    'empty' => false,
    'show' => true,
    'list' => true,
    'type' => 'int',
    'comment' => '运费模板ID',
    'default' => '',
    'SO' => false,
  ),
  'shop_id' => 
  array (
    'field' => 'shop_id',
    'label' => '商户ID',
    'pk' => false,
    'add' => true,
    'edit' => true,
    'html' => true,
    'empty' => false,
    'show' => true,
    'list' => true,
    'type' => 'int',
    'comment' => '商户ID',
    'default' => '',
    'SO' => false,
  ),
  'region_names' => 
  array (
    'field' => 'region_names',
    'label' => '配送区域名称',
    'pk' => false,
    'add' => true,
    'edit' => true,
    'html' => true,
    'empty' => false,
    'show' => true,
    'list' => true,
    'type' => 'text',
    'comment' => '配送区域名称',
    'default' => '',
    'SO' => false,
  ),
  'region_ids' => 
  array (
    'field' => 'region_ids',
    'label' => '配送区域ID',
    'pk' => false,
    'add' => true,
    'edit' => true,
    'html' => true,
    'empty' => false,
    'show' => true,
    'list' => true,
    'type' => 'text',
    'comment' => '配送区域ID',
    'default' => '',
    'SO' => false,
  ),
  'first' => 
  array (
    'field' => 'first',
    'label' => '首件(个)',
    'pk' => false,
    'add' => true,
    'edit' => true,
    'html' => true,
    'empty' => false,
    'show' => true,
    'list' => true,
    'type' => 'int',
    'comment' => '首件(个)',
    'default' => '',
    'SO' => false,
  ),
  'first_price' => 
  array (
    'field' => 'first_price',
    'label' => '首件运费',
    'pk' => false,
    'add' => true,
    'edit' => true,
    'html' => true,
    'empty' => false,
    'show' => true,
    'list' => true,
    'type' => 'number',
    'comment' => '首件运费',
    'default' => '0.00',
    'SO' => false,
  ),
  'renew' => 
  array (
    'field' => 'renew',
    'label' => '续件(个)',
    'pk' => false,
    'add' => true,
    'edit' => true,
    'html' => true,
    'empty' => false,
    'show' => true,
    'list' => true,
    'type' => 'int',
    'comment' => '续件(个)',
    'default' => '',
    'SO' => false,
  ),
  'renew_price' => 
  array (
    'field' => 'renew_price',
    'label' => '续件运费',
    'pk' => false,
    'add' => true,
    'edit' => true,
    'html' => true,
    'empty' => false,
    'show' => true,
    'list' => true,
    'type' => 'number',
    'comment' => '续件运费',
    'default' => '0.00',
    'SO' => false,
  ),
    'orderby' => 
  array (
    'field' => 'orderby',
    'label' => '排序',
    'pk' => false,
    'add' => true,
    'edit' => true,
    'html' => false,
    'empty' => true,
    'show' => true,
    'list' => true,
    'type' => 'int',
    'comment' => '排序',
    'default' => '50',
    'SO' => '=',
  ),
  'closed' => 
  array (
    'field' => 'closed',
    'label' => '删除标识',
    'pk' => false,
    'add' => true,
    'edit' => true,
    'html' => true,
    'empty' => false,
    'show' => true,
    'list' => true,
    'type' => 'int',
    'comment' => '删除标识',
    'default' => '',
    'SO' => false,
  ),
  'dateline' => 
  array (
    'field' => 'dateline',
    'label' => '创建时间',
    'pk' => false,
    'add' => true,
    'edit' => false,
    'html' => true,
    'empty' => false,
    'show' => true,
    'list' => true,
    'type' => 'dateline',
    'comment' => '创建时间',
    'default' => '',
    'SO' => false,
  ),
);