<?php
/**
 * Copy Right IJH.CC
 * Each engineer has a duty to keep the code elegant
 * $Id$
 */

if(!defined('__CORE_DIR')){
    exit("Access Denied");
}

return array (
  'shop_id' => 
  array (
    'field' => 'shop_id',
    'label' => '商户ID',
    'pk' => true,
    'add' => true,
    'edit' => false,
    'html' => false,
    'empty' => false,
    'show' => true,
    'list' => true,
    'type' => 'int',
    'comment' => '商户ID',
    'default' => '',
    'SO' => '=',
  ),
  'city_id' => 
  array (
    'field' => 'city_id',
    'label' => '城市ID',
    'pk' => false,
    'add' => true,
    'edit' => true,
    'html' => false,
    'empty' => true,
    'show' => true,
    'list' => true,
    'type' => 'int',
    'comment' => '城市ID',
    'default' => '',
    'SO' => '=',
  ),
  'tmpl_type' => 
  array (
    'field' => 'tmpl_type',
    'label' => '模板类型',
    'pk' => false,
    'add' => true,
    'edit' => true,
    'html' => false,
    'empty' => false,
    'show' => true,
    'list' => true,
    'type' => 'text',
    'comment' => '显示模板类型： market:商超,waimai:外卖',
    'default' => '',
    'SO' => '=',
  ),
  'cate_id' => 
  array (
    'field' => 'cate_id',
    'label' => '分类ID',
    'pk' => false,
    'add' => true,
    'edit' => true,
    'html' => false,
    'empty' => false,
    'show' => true,
    'list' => true,
    'type' => 'int',
    'comment' => '分类ID',
    'default' => '',
    'SO' => '=',
  ),
  'title' => 
  array (
    'field' => 'title',
    'label' => '商户名称',
    'pk' => false,
    'add' => true,
    'edit' => true,
    'html' => false,
    'empty' => false,
    'show' => true,
    'list' => true,
    'type' => 'text',
    'comment' => '商户名称',
    'default' => '',
    'SO' => 'like',
  ),
  'banner' => 
  array (
    'field' => 'banner',
    'label' => 'banner',
    'pk' => false,
    'add' => true,
    'edit' => true,
    'html' => false,
    'empty' => true,
    'show' => true,
    'list' => true,
    'type' => 'photo',
    'comment' => 'banner',
    'default' => '',
    'SO' => false,
  ),
  'logo' => 
  array (
    'field' => 'logo',
    'label' => '商户LOGO',
    'pk' => false,
    'add' => true,
    'edit' => true,
    'html' => false,
    'empty' => false,
    'show' => true,
    'list' => true,
    'type' => 'photo',
    'comment' => '商户LOGO',
    'default' => '',
    'SO' => false,
  ),
  'addr' => 
  array (
    'field' => 'addr',
    'label' => '地址',
    'pk' => false,
    'add' => true,
    'edit' => true,
    'html' => false,
    'empty' => true,
    'show' => true,
    'list' => true,
    'type' => 'text',
    'comment' => '地址',
    'default' => '',
    'SO' => false,
  ),
  'views' => 
  array (
    'field' => 'views',
    'label' => '浏览次数',
    'pk' => false,
    'add' => true,
    'edit' => true,
    'html' => false,
    'empty' => true,
    'show' => true,
    'list' => true,
    'type' => 'int',
    'comment' => '浏览次数',
    'default' => '',
    'SO' => 'between',
  ),
  'orders' => 
  array (
    'field' => 'orders',
    'label' => '订单数',
    'pk' => false,
    'add' => true,
    'edit' => true,
    'html' => false,
    'empty' => true,
    'show' => true,
    'list' => true,
    'type' => 'int',
    'comment' => '订单数',
    'default' => '',
    'SO' => 'between',
  ),
  'comments' => 
  array (
    'field' => 'comments',
    'label' => '评论数',
    'pk' => false,
    'add' => true,
    'edit' => true,
    'html' => false,
    'empty' => true,
    'show' => true,
    'list' => true,
    'type' => 'int',
    'comment' => '评论数',
    'default' => '',
    'SO' => 'between',
  ),
  'praise_num' => 
  array (
    'field' => 'praise_num',
    'label' => '好评数',
    'pk' => false,
    'add' => true,
    'edit' => true,
    'html' => false,
    'empty' => true,
    'show' => true,
    'list' => true,
    'type' => 'int',
    'comment' => '好评数',
    'default' => '',
    'SO' => 'between',
  ),
  'score' => 
  array (
    'field' => 'score',
    'label' => '总评分',
    'pk' => false,
    'add' => true,
    'edit' => true,
    'html' => false,
    'empty' => true,
    'show' => true,
    'list' => true,
    'type' => 'int',
    'comment' => '综合总评分，星星可以除以 评论数',
    'default' => '',
    'SO' => 'between',
  ),
  'score_fuwu' => 
  array (
    'field' => 'score_fuwu',
    'label' => '服务评分',
    'pk' => false,
    'add' => true,
    'edit' => true,
    'html' => false,
    'empty' => true,
    'show' => true,
    'list' => true,
    'type' => 'int',
    'comment' => '服务评分',
    'default' => '',
    'SO' => 'between',
  ),
  'score_kouwei' => 
  array (
    'field' => 'score_kouwei',
    'label' => '口味评分',
    'pk' => false,
    'add' => true,
    'edit' => true,
    'html' => false,
    'empty' => true,
    'show' => true,
    'list' => true,
    'type' => 'int',
    'comment' => '口味评分',
    'default' => '',
    'SO' => 'between',
  ),
  'first_amount' => 
  array (
    'field' => 'first_amount',
    'label' => '首单优惠',
    'pk' => false,
    'add' => true,
    'edit' => true,
    'html' => false,
    'empty' => true,
    'show' => true,
    'list' => true,
    'type' => 'number',
    'comment' => '首单优惠',
    'default' => '0.00',
    'SO' => false,
  ),
  'min_amount' => 
  array (
    'field' => 'min_amount',
    'label' => '起送价',
    'pk' => false,
    'add' => true,
    'edit' => true,
    'html' => false,
    'empty' => true,
    'show' => true,
    'list' => true,
    'type' => 'number',
    'comment' => '起送价',
    'default' => '0.00',
    'SO' => 'between',
  ),
  'freight' => 
  array (
    'field' => 'freight',
    'label' => '运费',
    'pk' => false,
    'add' => true,
    'edit' => true,
    'html' => false,
    'empty' => true,
    'show' => true,
    'list' => true,
    'type' => 'number',
    'comment' => '运费',
    'default' => '0.00',
    'SO' => false,
  ),
  'pei_amount' => 
  array (
    'field' => 'pei_amount',
    'label' => '配送费用',
    'pk' => false,
    'add' => true,
    'edit' => true,
    'html' => false,
    'empty' => true,
    'show' => true,
    'list' => true,
    'type' => 'number',
    'comment' => '配送费用 0:免配送费，支付第三方运费',
    'default' => '0.00',
    'SO' => false,
  ),
  'pei_time' => 
  array (
    'field' => 'pei_time',
    'label' => '平均等待时间',
    'pk' => false,
    'add' => true,
    'edit' => true,
    'html' => false,
    'empty' => true,
    'show' => true,
    'list' => true,
    'type' => 'int',
    'comment' => '分钟，平均等待时间,从商家接单开始到订单结束',
    'default' => '',
    'SO' => false,
  ),
  'pei_distance' => 
  array (
    'field' => 'pei_distance',
    'label' => '配送距离',
    'pk' => false,
    'add' => true,
    'edit' => true,
    'html' => false,
    'empty' => true,
    'show' => true,
    'list' => true,
    'type' => 'number',
    'comment' => '配送距离',
    'default' => '',
    'SO' => false,
  ),
  'pei_type' => 
  array (
    'field' => 'pei_type',
    'label' => '配送类型',
    'pk' => false,
    'add' => true,
    'edit' => true,
    'html' => false,
    'empty' => true,
    'show' => true,
    'list' => true,
    'type' => 'int',
    'comment' => '配送类型  0:自己送,1:第三方送，2:第三方代购及配送  3:用户自提单',
    'default' => '',
    'SO' => '=',
  ),
  'yy_status' => 
  array (
    'field' => 'yy_status',
    'label' => '营业状态',
    'pk' => false,
    'add' => true,
    'edit' => true,
    'html' => false,
    'empty' => true,
    'show' => true,
    'list' => true,
    'type' => 'int',
    'comment' => '营业状态  0:打烊，1：营业中',
    'default' => '',
    'SO' => '=',
  ),
  'yy_stime' => 
  array (
    'field' => 'yy_stime',
    'label' => '开始营业时间',
    'pk' => false,
    'add' => true,
    'edit' => true,
    'html' => false,
    'empty' => true,
    'show' => true,
    'list' => true,
    'type' => 'text',
    'comment' => '开始营业时间',
    'default' => '9:00',
    'SO' => 'betweendate',
  ),
  'yy_ltime' => 
  array (
    'field' => 'yy_ltime',
    'label' => '打烊时间',
    'pk' => false,
    'add' => true,
    'edit' => true,
    'html' => false,
    'empty' => true,
    'show' => true,
    'list' => true,
    'type' => 'text',
    'comment' => '打烊时间',
    'default' => '20:00',
    'SO' => 'betweendate',
  ),
  'yy_xiuxi' => 
  array (
    'field' => 'yy_xiuxi',
    'label' => '中间休息时间',
    'pk' => false,
    'add' => true,
    'edit' => true,
    'html' => false,
    'empty' => true,
    'show' => true,
    'list' => true,
    'type' => 'text',
    'comment' => '中间休息时间',
    'default' => '',
    'SO' => 'betweendate',
  ),
  'is_new' => 
  array (
    'field' => 'is_new',
    'label' => '是否新店铺',
    'pk' => false,
    'add' => true,
    'edit' => true,
    'html' => false,
    'empty' => true,
    'show' => true,
    'list' => true,
    'type' => 'int',
    'comment' => '是否新店铺  1:表示新店',
    'default' => '',
    'SO' => '=',
  ),
  'online_pay' => 
  array (
    'field' => 'online_pay',
    'label' => '是否支持在线支付',
    'pk' => false,
    'add' => true,
    'edit' => true,
    'html' => false,
    'empty' => true,
    'show' => true,
    'list' => true,
    'type' => 'int',
    'comment' => '是否支持在线支付 0:不支持在线支付，1：支持在线支付',
    'default' => '',
    'SO' => false,
  ),
  'youhui' => 
  array (
    'field' => 'youhui',
    'label' => '优惠信息冗余',
    'pk' => false,
    'add' => true,
    'edit' => true,
    'html' => false,
    'empty' => true,
    'show' => true,
    'list' => true,
    'type' => 'text',
    'comment' => '优惠信息冗余',
    'default' => '',
    'SO' => false,
  ),
  'info' => 
  array (
    'field' => 'info',
    'label' => '店铺简介',
    'pk' => false,
    'add' => true,
    'edit' => true,
    'html' => true,
    'empty' => true,
    'show' => true,
    'list' => true,
    'type' => 'text',
    'comment' => '',
    'default' => '',
    'SO' => false,
  ),
  'delcare' => 
  array (
    'field' => 'delcare',
    'label' => '店铺公告',
    'pk' => false,
    'add' => true,
    'edit' => true,
    'html' => true,
    'empty' => true,
    'show' => true,
    'list' => true,
    'type' => 'text',
    'comment' => '',
    'default' => '',
    'SO' => false,
  ),
  'pmid' => 
  array (
    'field' => 'pmid',
    'label' => '递推ID',
    'pk' => false,
    'add' => true,
    'edit' => true,
    'html' => false,
    'empty' => true,
    'show' => true,
    'list' => true,
    'type' => 'text',
    'comment' => '格式为(M|P|D|S)+ID M:会员，D:地推，S:商家，P:配送员',
    'default' => '',
    'SO' => false,
  ),
  'verify_name' => 
  array (
    'field' => 'verify_name',
    'label' => '验证状态',
    'pk' => false,
    'add' => true,
    'edit' => true,
    'html' => false,
    'empty' => true,
    'show' => true,
    'list' => true,
    'type' => 'int',
    'comment' => '0:未验证,1:已验证',
    'default' => '',
    'SO' => '=',
  ),
  'audit' => 
  array (
    'field' => 'audit',
    'label' => '审核状态',
    'pk' => false,
    'add' => true,
    'edit' => true,
    'html' => false,
    'empty' => true,
    'show' => true,
    'list' => true,
    'type' => 'int',
    'comment' => '商户是否审核 0:未审核，1:已审核',
    'default' => '',
    'SO' => '=',
  ),
  'closed' => 
  array (
    'field' => 'closed',
    'label' => '删除标识',
    'pk' => false,
    'add' => false,
    'edit' => false,
    'html' => false,
    'empty' => true,
    'show' => true,
    'list' => true,
    'type' => 'int',
    'comment' => '删除标识',
    'default' => '',
    'SO' => false,
  ),
  'clientip' => 
  array (
    'field' => 'clientip',
    'label' => '客户IP',
    'pk' => false,
    'add' => false,
    'edit' => false,
    'html' => false,
    'empty' => false,
    'show' => true,
    'list' => true,
    'type' => 'clientip',
    'comment' => '客户IP',
    'default' => '',
    'SO' => false,
  ),
  'dateline' => 
  array (
    'field' => 'dateline',
    'label' => '创建时间',
    'pk' => false,
    'add' => false,
    'edit' => false,
    'html' => false,
    'empty' => false,
    'show' => true,
    'list' => true,
    'type' => 'unixtime',
    'comment' => '创建时间',
    'default' => '',
    'SO' => 'betweendate',
  ),
    'phone' => 
  array (
    'field' => 'phone',
    'label' => '客服电话',
    'pk' => false,
    'add' => true,
    'edit' => true,
    'html' => false,
    'empty' => true,
    'show' => true,
    'list' => true,
    'type' => 'phone',
    'comment' => '客服电话',
    'default' => '',
    'SO' => 'false',
  ),
    'freight_stage' => 
  array (
    'field' => 'freight_stage',
    'label' => '配送费',
    'pk' => false,
    'add' => true,
    'edit' => true,
    'html' => true,
    'empty' => true,
    'show' => true,
    'list' => true,
    'type' => 'text',
    'comment' => '配送费',
    'default' => '',
    'SO' => 'false',
  ),
'is_daofu' => 
  array (
    'field' => 'is_daofu',
    'label' => 'is_daofu',
    'pk' => false,
    'add' => true,
    'edit' => true,
    'html' => false,
    'empty' => true,
    'show' => true,
    'list' => true,
    'type' => 'int',
    'comment' => '是否支持货到付款，0不支持，1支持',
    'default' => '',
    'SO' => 'false',
  ),
  'is_ziti' => 
  array (
    'field' => 'is_ziti',
    'label' => 'is_ziti',
    'pk' => false,
    'add' => true,
    'edit' => true,
    'html' => false,
    'empty' => true,
    'show' => true,
    'list' => true,
    'type' => 'int',
    'comment' => '是否支持到店自提，0不支持，1支持',
    'default' => '',
    'SO' => 'false',
  ),
  'orderby' => 
  array (
    'field' => 'orderby',
    'label' => 'orderby',
    'pk' => false,
    'add' => true,
    'edit' => true,
    'html' => false,
    'empty' => true,
    'show' => true,
    'list' => true,
    'type' => 'int',
    'comment' => '排序',
    'default' => '',
    'SO' => '=',
  ),
);